### ISSUE TITLE
Migrate CI back to OSS

### ISSUE THREAD

**Issue by drdelambre** [influxdata/ui#1007]
everytime a change is made in a branch within the ui, our e2e tests get run against idpe's master branch
everytime a change is made in a branch within idpe, those same tests get run against the ui's master branch

this relationship is super dope and pushes the potential system wide breakage back to the person who unknowingly introduces it. we should have it for OSS too.

we currently have monitor-ci running the e2e tests against oss on every branch, the work is to copy that infrastructure over to influxdb and make that repo run the e2e changes against the ui's master branch on every change over there

**Comment by genehynson** [comment]
To achieve this we need to do two things: 

1) We would just need to add a job to the OSS CI that executes [this script](https://github.com/influxdata/ui/blob/master/scripts/run-monitor-ci-tests.bash) in the UI repo. The config for this job is [defined here](https://github.com/influxdata/ui/blob/master/.circleci/config.yml#L518) and could just be copied over to the OSS Circle config. The only change (I think) would be to update `UI_BRANCH=${CIRCLE_BRANCH}` to `UI_BRANCH=master` so that we're testing the OSS changes against UI's latest

2) We need to make it influxdb image [defined here](https://github.com/influxdata/monitor-ci/blob/master/compose/fig.oss.yml#L40) customizable so that we can pull the influxdb image at a specific influxdb sha.

I think that's it?

**Comment by wbaker85** [comment]
From the OSS side, we'll also need to change our CI to actually build a docker image to use for the e2e testing.

Currently we do: `[build OSS (as a go binary)]` -> `[run e2e tests against the go binary]`.
We should be able to do something like `[build OSS (as a go binary)]` -> `[build a docker image from the binary]` -> `[run e2e tests using the script]`.

If the the entire CI is successful and it's on the master branch (or one of the release branches), we could then push the image built for the e2e testing so it could be used by the `ui` repo side. From the master branch maybe we could call it something like `oss-master:acceptance` for the master branch, and `oss-2.0:acceptance` for release branches.

**Comment by drdelambre** [comment]
re image naming: you'd wanna flip that precedence so that the tag reference is the thing that's changing. ie: oss-acceptance:latest (for master) and oss-acceptance:2.0 (for named releases). we usually also add an oss-acceptance:${GIT SHA} on all successful master builds in case we have to version lock for some reason.

re building: any reason not to have it built right into a docker image? we defined this one for oss local developement: https://github.com/influxdata/monitor-ci/blob/master/docker/Dockerfile.influx. does that still encompass the build process? obviously it should live in the oss repo and not in monitor-ci to better encapsulate the service (something we are currently doing for `ui` as well).

@genehynson why would the frontend build on an api change instead of using the `:latest` image that is publish from master? i have no opinion on making the existing pipeline more flexible vs cloning it, just seems like we wouldn't want to be building every commit for every repo on every change, and that we can offload a bit of that onto the docker registry

**Comment by genehynson** [comment]
Yeah right now the `monitor-ci` pipeline is going to build an image regardless if the image already exists in quay for a given sha. We could totally improve upon that by checking quay first before building the image. I don't think that's a blocker tho, just an optimization

**Comment by genehynson** [comment]
@wbaker85 If possible I think we would want to start the UI tests in the OSS pipeline sooner rather than later. I would think they could execute in parallel after the image is built. The `monitor-ci` pipeline takes ~30min right now. Waiting until all the other tests pass to start it could make the OSS pipeline take much too long to complete.

**Comment by wbaker85** [comment]
@drdelambre good call on the image naming. Also regarding the building, the only reason to not build OSS directly into an image as it stands is that there are a couple other non-e2e tests that use the built binary later on. So as it is, we could just restore the built binary from the cache and wrap it in a docker image, then save that for use later. The [Dockerfile](https://github.com/influxdata/influxdb/blob/master/docker/influxd/Dockerfile) in OSS is currently set up to copy in the built binaries. Having an extra step to build the image would incur a minute or two of extra time for setting up a new environment though, so this could be an area of optimization - I honestly don't know if the additional tests that run on the binary could be run with a docker image instead or not.

@genehynson I don't love the idea of pushing an image to the registry on what would essentially be every single push, but I can see why that would be necessary vs. an alternative of having the `monitor-ci` pipeline build the OSS backend from source or something like that. Although I will say that building OSS doesn't take all that long (~5 min). Definitely agree about starting the UI tests ASAP also! ~30 min for the `monitor-ci` pipeline is a bit yikes...seems like there is a lot of stuff that runs in the `monitor-ci` pipeline currently that wouldn't be relevant when just considering a change to the OSS backend - all the UI vs cloud tests etc. Would there be any practical way to have a slimmed-down verison of the pipeline run for OSS-only changes? Maybe not...just brainstorming.

**Comment by genehynson** [comment]
Yeah I don't think we would want the UI pipeline to have the responsibility of building the OSS image - that seems like an unnecessary coupling between those products. Good idea about a slimmed-down version of the pipeline for OSS stuff only. The cloud stuff actually takes the longest. Without it I think the pipeline would be about ~15min in length (5min to build UI image, 10min to run ui-oss tests). And if we optimize the pipeline to pull the latest built image from UI's master instead of re-building it every time we could get the pipeline down to 10min!
