### ISSUE TITLE
Dashboard variable dropdowns don't always fit value lengths

### ISSUE THREAD

**Issue by samhld** [influxdata/ui#1065]
Minor nit.  Here is what I mean:

![Screen Shot 2021-03-31 at 8 56 10 PM](https://user-images.githubusercontent.com/4852912/113241521-c5083880-9263-11eb-84e2-c395af3c8748.png)

**Comment by samhld** [comment]
@jrenee42 explained to me why this is the case -- makes sense!  I'll close this for now.

**Comment by jrenee42** [comment]
although keeping it open is ok; just because we know why this is happening doesn't mean it cannot be improved:

if it’s a csv value (loaded immediately) then it should be wide enough
but we can make them all wider (have a bigger minimum width)

something to talk with the design team about; but definitely not as important as the other fixes that just went in

**Comment by jrenee42** [comment]
explanation: if it’s via a query, then we don’t know the width/values at render time;
(using the placeholder text for the width and/or the values if they are known immediately)

so if we adjusted after the values came in then they would change and it might look bad
but when you hit the down arrow it’s wide enough

**Comment by kristinarobinson** [comment]
Now replaced with type ahead.
