### ISSUE TITLE
Annotations: Depending on where you hover, annotations display on top of each other

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#1117]
I had two annotations fairly close to each other, and sometimes when I hover, both of them display on top of each other - see screenshot.
![Screen Shot 2021-04-05 at 12 28 13 PM](https://user-images.githubusercontent.com/13143006/113616901-92b35e00-960a-11eb-82e3-83c70383f255.png)

**Comment by daviddkkim** [comment]
Chatted with Bucky but writing down here for the sake of documentation:

If multiple tooltip would be "Triggered" due to the hover magin of two close annotations, only 1 will show (Potential rule for this is "first one hovered opened stays opened" or "closest one from hovered point" or etc).

 If the user wants to hover open the other one, the user has few options:
 - They can move mouse to the part of the annotation hover range that only has that one annotation within the range.
 - They can zoom in and do the same
 - They can move mouse away and re-enter the hover range so that they open the one they want to see first.
