### ISSUE TITLE
Feature Request: Automate changelogging

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#113]
### Background
Currently, our process for change logging is to create a PR, consider if the change belongs in changelog, add an entry, then force push the whole thing, referencing the PR.

Until late September, we didn't have a changelog in ui at all. It's an important concept for product and product marketing, but it's something we've let slide as engineers.

### Considerations
For a changelog to reference the PR it's part of, the PR has to be created before it can be linked in the changelog.

The relevant entries to include are `feat` and `fix`.

Should this be fully automated, or a script someone has to run?

**Comment by kristinarobinson** [comment]
I'm confused.  No one should be coding with an Issue in ZenHub.  The ChangeLog should refer back to the ZenHub issue, not the PR.  Every Changelog entry should be a one to one correlation with a PR, which you are correct, may or may not have been created prior to the changelog entry.  ChangeLog entries are issue driven:  x was fixed, y chore was completed, z feature introduced.  By nature of the tagging, you should always be able to get back to the PR, based on the version.

**Comment by kristinarobinson** [comment]
W.r.t. running a script or having it all automated.  My only concern is if we automated, when would have happen?  Our E2E tests are failing frequently right now, so that's not a guaranteed success gate.  We *could* put it on the push to master, and there's a package that will do that, hooking into Circle-CI (semantic-release).  However, we lose all control over the versioning does, and rely only on the -feat / -fix / -chore, etc.  Given that we like to do feature flags, and other interesting rollouts, I hesitate to automate that piece when breaking changes might not be really breaking.

**Comment by hoorayimhelping** [comment]
>the ChangeLog should refer back to the ZenHub issue, not the PR.

I don't think that's right. The changelog is a public document that contains user-facing changes. We link to the PR because it's an open source project and we can link a feature directly to the code that implemented that feature.

**Comment by jzahnd** [comment]
@hoorayimhelping is this still something on your mind? I am closing out some old issues but we can leave this one open if it is important on your list

**Comment by jzahnd** [comment]
Closing for now, we can reopen if this is a priority.
