### ISSUE TITLE
User input for aggregation interval in Define Query for checks in UI 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/ui#1199]
**Proposal:**
Allow users to change the auto(time in seconds) interval in the UI when creating checks. Include text to clarify that this interval is the same as the **Schedule Every** configuration option. 

**Current behavior:**
When a user creates a new check through the UI, a default aggregation interval is applied. This interval matches the **Schedule Every** configuration option in the next step. However, some users find the inability to adjust this interval on the fist step (define query) as a hurdle which blocks them from finishing the check configuration. 
<img width="1272" alt="Screen Shot 2021-04-13 at 12 42 17 PM" src="https://user-images.githubusercontent.com/30506042/114596863-bd7a6380-9c55-11eb-8f1e-5c42a21d23e2.png">

**Desired behavior:**
Allow users to change the aggregation interval on the **Define Query** step which then is reflected in the **Configure Check** step. 

**Alternatives considered:**
Include text which describes why the user can't configure the aggregation interval in the first step. 

**Use case:**
Why is this important this UX hinders some users from completing the steps towards check creation.

**Comment by kramik1** [comment]
I was playing with my local instance of influxdb2 and I do not see the schedule every field influencing this value. I think it might be driven by the query response size. I did a large query over 7 days in data explorer and the default window was 30m. I think adding some type of either informational notice about why it is not customizable or enabling it would be helpful. Right now, some people are really confused by this.

**Comment by Anaisdg** [comment]
Hello @kramik1 this feature request is a proposal for the UI in the checks panel in the **Alerts** page. You're right in the **Data Explorer**, the aggregation interval relative to the query duration/response size. To change it in the **Data Explorer**, you can click **Custom** and input your own aggregation interval. Alternatively, you can view the **Script Editor** and edit the underlying Flux. 
<img width="1262" alt="Screen Shot 2021-04-13 at 2 54 45 PM" src="https://user-images.githubusercontent.com/30506042/114612852-40a4b500-9c68-11eb-9b46-bfc88390046e.png">

**Comment by kramik1** [comment]
Right, I am comparing the data explorer to the alert UI. It seems that although they look similar they are working differently in the background.

**Comment by rlkennedyreid** [comment]
My interpretation of the documentation is that your proposal is actually how the alerts page should work already.

https://docs.influxdata.com/influxdb/v2.0/monitor-alert/checks/create/

I agree it does not, and reported the issue myself (issue #535). I have the experience that @kramik1 has reported, where the 'schedule every' option doesn't change the window. But I'm definitely on the alerts page, not the data explorer page.

I don't know if attempts have been made to reproduce the issue, but I've consistently reproduced it on different systems, and never been able to get different behaviour.

Because you don't have CLI implementation of check creating, this effectively renders your checks/alerts system useless, as far as I can tell. Because the window over which you'd like to do alerts NEEDS to be customisable, how could influxDB possibly make a reasonable judgement call on how often you need a check to be made for arbitrary time-series data?

**Comment by rcastill** [comment]
+1

In fact I would like to put an emphasis on what @rlkennedyreid said:

> where the 'schedule every' option doesn't change the window

that is seriously broken behavior if you rely on the alerts system.

We tested and the window will always be of "1m", it can be seen in the time series rendered (as it won't change if the value is changed) and also in behavior (window time for aggregations will remain 1m).

**Comment by itaross** [comment]
I am encoutering the same issue too, with a window period of 10s. 
Changing the "schedule every" is not modifying the behaviour.
This is very critical and makes the alerts feature cwompletely unacceptable for the users.

**Comment by hubertat** [comment]
+1

Same for me, this is broken and that's a serious issue.
It's difficult to create functioning alerts now.

**Comment by kristinarobinson** [comment]
This functionality is now available in Notebooks.  If you go to the Notebooks section, you can select a `Set an Alert` template, and have control over both period and offset.
