### ISSUE TITLE
Epic: Auto Refresh Dashboard / Pause Cells 

### ISSUE THREAD

**Issue by ShmuelLotman** [influxdata/ui#1207]
### User Story
   As a user, I am now able to interact with my dashboards in a more dynamic way, display them on monitors with greater ease, maintain a more firm grasp of my query totals and overall costs, and acquire more granular control over individual cells within my dashboard. 

### Context

Approximately a year or so ago, we provided users with the ability to set dashboards to refresh at preset intervals automatically. While this was a convenient way to interact with dashboards, the frequent complaint was that users would leave their pages open overnight or otherwise unattended and thus accrue significant charges on their account. As a response to this, we disabled the feature entirely. 

During subsequent exploration of dashboard feature sets, the opportunity to reintroduce this feature presented itself as a natural extension to the work on refreshing individual cells, as a way to further expand the available features dashboard view provided to users. 

Furthermore, due to the existing query cache structure, the ability to pause cells, thereby removing them from the cycle of automatic refreshes, (as well as resume), is something that can be integrated rather seamlessly into the work scoped out within this epic. 

### Acceptance Criteria 
 In order to re-enable this feature, it is critical we address the primary concern of abandoned dashboards and runaway query totals. This can be tackled from two perspectives:
 1.  A two-step process to enable auto refresh, with clearly labeled steps that, by definition, mean a user has the clear intention to enable this feature
 2.  The ability to add an "inactivity timeout," such that a user who leaves a dashboard for a particular amount of time can be assured that their query totals will not continue to increase past an acceptable point in their absence. 

Additionally, the two-step process should provide a user with the ability to set a duration, which will serve as a hard stop on their auto refresh process, as well as the ability to set the refresh frequency. 

Finally, as mentioned above, users should be able to pause cells, thereby removing them from the auto refresh polling system, and resume them, which will put them back into the same flow. 

## Summary
 The following is a list of features required for an MVP of this feature set: 
  1. ** Two step process to enable auto refresh **
  2. ** Ability to select auto refresh interval **
  3. ** Ability to select deadline (duration of refresh) after which auto refresh stops automatically **
  4. ** Ability to select inactivity timeout, which automatically stops a user's auto refresh process when hit**
  5. ** Ability to pause cells & resume them, which removes and replaces them in the refresh process, respectively **

### Extended Outlook
  While this feature does not encompass the full potential that additional controls may bring to dashboards, such as the ability to enable windows of time within which dashboards would refresh (among other features), this provides an opportunity to explore giving greater control to our users when it comes to their visualizations. If this is successful, further areas of exploration could include integration with the multi-user/org epic, wherein an admin user would be able to set predefined limitations on dashboard refresh settings, set settings for different kinds of visualizations, and so on. 

** Feature Flags **
1. newAutoRefresh
2. pauseCell

**Comment by Asalem1** [comment]
Some product decisions that we bumped into in the context of the pause cell functionality that we should consider before integrating that into the app.

### Background

Due to an inability to make direct changes to the API contract, the implementation of the pause-cell feature is dependent upon in-memory storage to maintain its state. More specifically, this feature makes use of the queryCache as a basis for caching the query, the query's corresponding results, and the paused state of the cell. This is problematic since it causes the query cache to be aware of view layer principles that have no bearing on the `query -> result` interaction and risks adding unnecessary complexity to this. In addition, this architectural issue presented some product level decisions that should be considered when implementing this feature. Primarily, we need a wholesale understanding of what a user expects when a cell is paused?

Within the context of the soon-to-be reenabled autorefresh functionality, the pause functionality seems to play a role in preventing the autorefresh functionality from rerunning a paused cell. However, we must address this feature as a standalone piece of infrastructure since there are implications beyond the autorefresh context that must be addressed. As such, we need to identify a user's expectations:

- What is the expectation of a paused cell in general? Should the state of that paused cell persist when navigating away from the dashboard page? Should the paused cell state be preserved across sessions (e.g. when a user logs in and out of our app)? These boundaries will need to be explored further
- What is the expectation of a paused cell that is being modified? IF a cell is modified in the VEO and saved, should the paused state persist?
- Where should the source of truth for a paused cell exist? Part of the responsibility surely depends upon the API to store the state of a paused cell, but we need to get a better understanding of what the expectations are for a paused cell? That is to say, that if a cell is paused and no data exists for the corresponding cell within the cache, do we expect to populate the cell with data from when it was paused? From when the screen was loaded?

These underlying questions should be addressed in order to get a better understanding of how to implement this feature within the app

**Comment by barbaranelson** [comment]
After a brief conversation with Shmuel, I agree that we should pause this feature.  It was a nice-to-have and it feels like it is opening a larger can of worms than we want at this stage. Let's hold on the pause-cell feature for now.
