### ISSUE TITLE
Maps: Importing template with Map viz type crashes dashboard

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1233]
Here's a dashboard template with a map type defined. When i try to load that template into an OSS instance, i am able to load it successfully, but when i load the dashboard, i get this error:
```
TypeError: Cannot destructure property 'graphic' of 'm.find(...)' as it is undefined.
    at p.getVewTypeGraphic (ViewTypeDropdown.tsx:101)
    at button (ViewTypeDropdown.tsx:38)
    at Dropdown.tsx:68
    at Zi (react-dom.production.min.js:150)
    at xo (react-dom.production.min.js:164)
    at Ro (react-dom.production.min.js:181)
    at Ga (react-dom.production.min.js:232)
    at Ka (react-dom.production.min.js:233)
    at Ns (react-dom.production.min.js:249)
    at Es (react-dom.production.min.js:248)
ha @ react-dom.production.min.js:198
```

![image](https://user-images.githubusercontent.com/4805997/115090198-1867c100-9ec9-11eb-855f-da3ddd0fb4df.png)

![image](https://user-images.githubusercontent.com/4805997/115090414-a6dc4280-9ec9-11eb-9be3-c450ecf0739b.png)

maps.yml
```
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: vibrant-mendel-7f3001
spec:
    charts:
      - allowPanAndZoom: true
        geoLayers:
          - colorDimension:
                label: Value
                name: color
            colorField: _value
            intensityDimension:
                name: intensity
            layerType: pointMap
            radiusDimension:
                name: radius
            viewColors:
              - hex: '#ff0000'
                type: min
              - hex: '#343aeb'
                value: 50
              - hex: '#343aeb'
                type: max
        height: 4
        kind: Geo
        name: Map
        queries:
          - query: |-
                from(bucket: "telegraf")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "iss")
                  |> filter(fn: (r) => r["_field"] == "iss_position_latitude" or r["_field"] == "iss_position_longitude")
                  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)
                  |> yield(name: "mean")
        staticLegend: {}
        width: 4
        zoom: 6
    name: Maps
```

to load in the cli, use the command `influx apply -c default -f maps.yml`

**Comment by wbaker85** [comment]
Which version of OSS are you loading this into @russorat?

When I try to load this template into a `v2.0.7` instance, I get this:

```
Error: Kind=Dashboard field=root[0].spec.charts[0].kind reason="invalid chart kind provided: geo".
```

...because the `geo` type is not in this list: https://github.com/influxdata/influxdb/blob/c72285b20a2d96b997ed7c2691154e6998d01f70/pkger/parser_models.go#L423. Seems reasonable really, since OSS doesn't have maps.

Another interesting thing is that if you build from `influxdb:master`, the `geo` type actually _is_ in the list (guess a PR never got backported into `2.0`?) - but I can't reproduce the behavior described in the issue running with master:

- Applying the template as-is, adding a couple datapoints to a new bucket called `telegraf`, and opening the dashboard results in this:

```
data added (lp via /api/v2/write):
iss iss_position_latitude=50.11496269845
iss iss_position_longitude=118.07900427317
```

<img width="616" alt="image" src="https://user-images.githubusercontent.com/55118525/123286012-889f4e00-d4db-11eb-888e-ebfdd877e0f1.png">

- Changing the fields to `lat` and `lon` both in the template and the data results in this, which is not very satisfying - but also doesn't crash the dashboard. OSS doesn't have a tile server so the "map" part is missing from the visualization :smile:

```
data added (lp via /api/v2/write):
iss lat=50.11496269845
iss long=118.07900427317
```

<img width="800" alt="image" src="https://user-images.githubusercontent.com/55118525/123286522-fba8c480-d4db-11eb-8887-fa384689b809.png"> 

I'd say we should probably make `pkger` continue to reject templates that have `geo` types in them, unless OSS ever gets support for map visualizations - this should be a 1-liner change. But I'm still interested in which version you are running and any other details you might be able to share since I can't reproduce the behavior you're seeing exactly.

**Comment by russorat** [comment]
i must have been testing with an earlier version. i get the same response in 2.0.7. thanks! closing.
