### ISSUE TITLE
Clicking on `View Raw Data` does not work in Checks/Alerting

### ISSUE THREAD

**Issue by subirjolly** [influxdata/ui#1241]
**Steps to reproduce:**
When creating a check, you can not `View Raw Data` if you are using column type as `number`. When you click on `View Raw Data`, it triggers a Redux change to enable raw data but the code in `Vis.tsx` disables the flag in Redux right after. So, gives an effect that the toggle is disabled whereas it's not.

**Expected behavior:**
Should allow you to View Raw Data when number column is being used.

**Actual behavior:**
![Kapture 2021-04-19 at 16 15 22](https://user-images.githubusercontent.com/1637395/115303909-3f74fb80-a132-11eb-95d2-340bb4932e9d.gif)

**Comment by Asalem1** [comment]
@russorat do we want to be able to view the raw data view of the checks visualization?

**Comment by Asalem1** [comment]
In investigating this it looks like we ended up disabling this due to an issue where deadman checks were rendering non-numeric fields that were crashing the raw data table. @russorat did we want to maintain the disabled view and re-enable the raw data view or did we want to keep it disabled until we address the raw data table issue for non-numeric values?

**Comment by russorat** [comment]
data should never crash the raw data view. We should enable this and if it crashes the raw data view, we should open an issue to fix the raw data view (or more likely, switch it over to simple table).

**Comment by Asalem1** [comment]
So it looks like what the original intent of the PR that disabled this view was to default the raw data view if a check's data included non-numeric values (since those can't be graphed by the XY Plot Graph, and were therefore crashing the browser).
