### ISSUE TITLE
Annotations: Annotation time should match the time in the hover legend

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1265]
When i add an annotation to a graph, the timestamp of the annotation should be the same time as the timestamp of the hover legend when i clicked the graph. Right now, they are different, and because the timezone settings don't match (#1264 ) it makes it difficult to reconcile.

![Kapture 2021-04-20 at 20 42 45](https://user-images.githubusercontent.com/4805997/115493835-53dff380-a219-11eb-99c7-8eb28ff51c26.gif)

**Comment by hoorayimhelping** [comment]
closed with #1232

**Comment by hoorayimhelping** [comment]
mistakenly closed the wrong issue

**Comment by hoorayimhelping** [comment]
There seem to be two issues here:

- the hover legent rounds the date based on the graph domain and annotations don't. I think this is what appears to be the timezone issue. If you adjust the date on the graph to 5 minutes, the issue becomes a little bit clearer, because the rounding error happens at a minute scale, not an hour scale.
- the time in the field is in 24 hour time, but the graph is 12 hour time
