### ISSUE TITLE
Annotations: Make initial UX more friendly

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1320]
### Background
The annotations toolbar and one-click annotations button ends up confusing people. They expect to be able to annotate the graph when they click the purple annotations button.

### Acceptance Criteria
- Default state: read mode on, write mode off, control bar is closed
- Clicking the Annotations toggle button opens the control bar and toggles write mode to on, and leaves read mode to on.
- Clicking the Annotations toggle button again closes the control bar and toggles both read mode and write mode *off*

**Comment by daviddkkim** [comment]
This is a good direction. 
I have another pattern idea that I'd like us to think about and compare against this one :

How about we keep both the read and write checkboxes and make it such that the default behavior when the annotations button is toggled is that both read and write boxes are checked and when the annotations button is toggled off, both read and write boxes are unchecked? 

Reasons for the interaction pattern: 
- I think what was confusing might have been that they expected everything to turn ON when they clicked the annotation button; instead, we selectively turned On the read but not the write. 
- I expect they would want the same behavior to be true when they turn off the toggle, everything turns OFF. Rather than just the write mode turning off.
- I think if we can avoid adding "double meaning" to a single button, it would be preferable. It's kind of in the realm of not abstracting our functionality in the UI too much and being direct. 

These are just my opinions/brain dump. Would love to hear your thoughts

**Comment by hoorayimhelping** [comment]
@daviddkkim  @jrenee42 

>they expected everything to turn ON when they clicked the annotation button; instead, we selectively turned On the read but not the write. 

First, to clear up any confusion, read mode for annotations is defaulted to on, even before the button is clicked. If you go to a link to a cell with an annotation, the annotation will render when you first visit the page. I'm not sure if you were aware that was the case, but that might explain some of the confusion I had about your proposed solution.

I wrote this part up before writing the above part:

> My main issue with David's proposed solution is that users need to have the toolbar open to see their annotations. I think that's kind of annoying and needy as a UX thing.

> Annotations are shown by default, so to follow this convention, we'll have to start with the toolbar open but not in write mode, which leaves us in a similar spot to the one we're in now.

**Comment by daviddkkim** [comment]
Yeah I understand your confusion - I think we can keep that same default behavior and add this new behavior on top of it and it won't be too confusing.

So then at the start, by default it will be (annotation button off, read mode on, write mode off) and then the first time the user clicks on annotations button to turn into,  we get (annotations button on, read mode on, write mode on), and the next time the user clicks on annotations button to turn it off, we get (annotations button off, read mode off, write mode off).  

The vibe I'm getting is that there won't be a "perfect" solution because of the edge cases around read/write/ zoom/ range so some trade off will need to happen here and there. Now that I've said that out loud and embraced that there probably isn't a perfect solution, I'm totally okay with going with your suggested approach if you believe that's the intuitive way to go. I think our users will be able to figure it out whichever way we go.

**Comment by daviddkkim** [comment]
The only "perfect" solution I can think of is to decouple the read and write mode from that one button. Make that button only a read mode thing and make writing annotations another action, like a popover option on a click on the graph. But this sounds like it would be a scooooooooope creep/ huge lift.
