### ISSUE TITLE
Annotations: I would like a notification when i try to add an annotation on a graph type that isn't supported

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1431]
Given i am on a dashboard and i have 1 click annotation enabled
when i click on a graph type that is not supported for annotations
then i get an alert telling me this graph type isn't supported for annotations.

Notes:
- once this is added, we should remove the static text from the dashboard page about supported types
- the text of the notification should be "This graph type does not support adding annotations."
- the notice should be a warning, and stick around for a few seconds, enough time to read the text, similar to deleting an asset

**Comment by jrenee42** [comment]
@daviddkkim  so this will be a toast notification?  (go on top, non-blocking, and do not need to dismiss it?)

**Comment by russorat** [comment]
yes, toast notification

**Comment by daviddkkim** [comment]
Yeah I think toast would be suitable.  

For the text, What do yall think about instead of saying "This graph type does not support adding annotations." , we say "Annotatons is supported for only XXX types "?   

Pros: 
- More clear what the user needs to do to use annotations (it would tell them exactly what graph type needs to be created) 

Cons:
- Everytime we support more graph types, we would need to update this message

**Comment by daviddkkim** [comment]
We could use this component: https://influxdata.github.io/clockface/?path=/story/atomic-notification--notification 
@jrenee42 

here's the design spec
![Screen Shot 2021-05-17 at 1 59 10 PM](https://user-images.githubusercontent.com/12561526/118556103-50f0f980-b718-11eb-9bed-02a4ed337d81.png)
