### ISSUE TITLE
Notebooks: Resize Query Builder Panel

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1565]
We would like ability to resize the vertical height of a query builder panel in Notebooks. Using the [LargeDraggableResizer](https://influxdata.github.io/clockface/?path=/story/layout-draggable-resizer-family--draggableresizer), a user should be able to resize the vertical height of the panel, while maintaining the original minimum height behavior.

## Acceptance Criteria

* When in a notebook with a query builder panel, a user should see a LargeDraggableResizer and have the ability to click and drag on the resizer. After clicking and dragging, the user should be able to increase the vertical height of the panel while maintaining the original behavior of the minimum height.

**Comment by drdelambre** [comment]
i don't understand how to do this with the LargeDraggableResizer or why that is defined in the requirements. That component subdivides a fixed size, which, after maximizing for interaction space, means that all notebooks will only be the height of a single page, and that making one panel larger will shrink the following panel, which i hope is not the desired behavior. That component was made for an interaction like the data explorer, in which you can see that making the visualization larger makes the query builder smaller.

**Comment by drdelambre** [comment]
![Screenshot from 2021-06-07 10-25-27.png](https://images.zenhubusercontent.com/5e3b1c99342de3102fa83e1d/bbb57f21-30ac-4f86-8b52-0e44169bdbda)

![Screenshot from 2021-06-07 10-24-34.png](https://images.zenhubusercontent.com/5e3b1c99342de3102fa83e1d/9bc28017-bbce-4be5-94bb-bfab5fa4fee2)

i'm confused at what the ask is here. are we making it where the query builder columns grow in length, and removing the resizer from the raw table results, giving it a fixed height?

or is the ask to change the interaction to where the panel grows, and then we subdivide the panel size using the LargeDraggableResizer? If that's the case, what happens when we have the results collapsed, or there is an error, or the panel hasn't run yet? does that still have a drag handle?

is the ask for there to be two independent sizes attached to this panel, so that both are dragged but no subdividing happens like in LargeDraggableResizer? this option also includes the same questions about the behavior of the other states for the result set / error piece of this
