### ISSUE TITLE
Notebooks: Resize Markdown Panel

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#1566]
We would like ability to resize the vertical height of a markdown panel in Notebooks. Using the [LargeDraggableResizer](https://influxdata.github.io/clockface/?path=/story/layout-draggable-resizer-family--draggableresizer), a user should be able to resize the vertical height of the panel, while maintaining the original minimum height behavior.

## Acceptance Criteria

* When in a notebook with a markdown panel, a user should see a LargeDraggableResizer and have the ability to click and drag on the resizer. After clicking and dragging, the user should be able to increase the vertical height of the panel while maintaining the original behavior of the minimum height.

**Comment by drdelambre** [comment]
i don't understand how to do this with the LargeDraggableResizer or why that is defined in the requirements. That component subdivides a fixed size, which, after maximizing for interaction space, means that all notebooks will only be the height of a single page, and that making one panel larger will shrink the following panel, which i hope is not the desired behavior. That component was made for an interaction like the data explorer, in which you can see that making the visualization larger makes the query builder smaller.

**Comment by juliajames12** [comment]
@drdelambre I agree. We definitely don't want to make the panels smaller below the panel being resized. Instead of the LargeDraggableResizer would it be helpful to use the action of the resizer that's currently used at the bottom of the simple table (but with the updated look and feel seen in the new LargeDraggableResizer)? I believe that functionality matches what we want, but I don't believe that is currently in our component library. https://images.zenhubusercontent.com/279622976/fbb52d06-64d9-4511-b4a5-f88ad11ebddb/screen_recording_2021_06_07_at_1_16_16_pm.mov
