### ISSUE TITLE
Epic: add metadata to Buckets page

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#1578]
### Target Customer / Background data / Context / Market Size
the target user for this feature is someone who is looking for storage information about their instance

### Goals
The goal of this epic is to incorporate the schema type information on a bucket

### Acceptance Crit
- as a user, i can see if a bucket is implicit or explicit schema type

### Notes
 - If no schema type is returned in the API, it should be assumed to be implicit schema.
 
### Release Plan
TBD

### Team
 - Anchor / Dev Champion @jrenee42 
 - Product Manager - @russorat 
 - Design - @daviddkkim

**Comment by russorat** [comment]
This issue might also be good to tackle as part of this: https://github.com/influxdata/ui/issues/2229

**Comment by russorat** [comment]
I've added this as an issue on a larger Explicit Schema epic. #2231

**Comment by jrenee42** [comment]
what it looks like: (just adding the schema type in the metadata section)
![Screen Shot 2021-08-05 at 12.17.12 PM.png](https://images.zenhubusercontent.com/5fbbf7579d1f2e09ec8ff6e2/bf2a964b-086d-4c63-8dc9-cee1485a8a53)

**Comment by daviddkkim** [comment]
@jrenee42  
Let's go with this ![Screen Shot 2021-08-05 at 2.49.36 PM.png](https://images.zenhubusercontent.com/604f76d7b2c0ce7a06471654/00391193-1540-4d97-9e1a-1c857c45d708) 

Russ pointed out that every meta data field is a key value pair so I think it makes sense to make the schema type to display as a key value pair !

So instead of "Implicit Schema Type", we display as "Schema Type: Implicit"
