### ISSUE TITLE
Flows TimeRange selections don't persist

### ISSUE THREAD

**Issue by Asalem1** [influxdata/ui#175]
### Problem

Currently a timerange selection doesn't persist when navigating to and from a flow:

![flows-timerange](https://user-images.githubusercontent.com/19984220/96178873-e3ac8a00-0ee4-11eb-9ca7-67c7da00f034.gif)

**Comment by Asalem1** [comment]
This is blocked until this PR gets across the line:

https://github.com/influxdata/ui/pull/187

**Comment by Asalem1** [comment]
This "bug" might not actually be a bug since it opens a new concept of how the time range is integrated into flows. We need some design (conceptual) to understand what the role of the time range dropdown is and whether / how it should persist (if at all)

**Comment by alexpaxton** [comment]
I vote to have the time range stored with the Flow. I think this better represents what is happening in the flow.

For example if the user is creating a task, the time range will appear in the exported task, and it would be unexpected for it to change outside of user intention

There might be some downside to persisting the time range in this way, but I can't think of it yet.

**Comment by drdelambre** [comment]
preface: not arguing the choice, just wanna make sure we're on the same page, and that info has been shared.

talking to russ, that assumption of time <> task relation is incorrect in our current usage.

Usually (by a very high margin) the time a task operates on is "everything since the last time the task ran", or in his words `-task.every`. So there's a distinction between the time value the user is exploring and the task that gets generated. Maybe you need to look at a full months of data to find something interesting that happened a week ago, but you only need to downsample "new" data to trigger an alert on that condition. There's also an offset that we didn't account for (but isn't widely used), so a task's definition of time involves; a frequency + a window size (usually the same as the frequency) + an offset (usually 0). 

this ties into the talks of: is a flow an artifact, or does it generate artifacts? and if it is an artifact itself, what does that artifact represent? A context? from what perspective?

Which begs the question about exploration... is the time window you are exploring a transient artifact of a lightweight process (where a flow is just as valuable at time `tn` as it was at time `t0`, or is it a frame around the definition of the context built while creating a flow (where time is a critical aspect of discovery). ie. "what created this outage in the last hour" across multiple flows vs "always show me these conditions against the past hour)

**Comment by drdelambre** [comment]
save the time range to a flow
