### ISSUE TITLE
`cloud-e2e-firefox` e2e tests need to run tests from "cloud" as well as shared

### ISSUE THREAD

**Issue by wbaker85** [influxdata/ui#1808]
I discovered while working on https://github.com/influxdata/ui/pull/1807 that the `cloud-e2e-firefox` job only runs tests from the "shared" folder and not the "cloud" folder as well. I found this out because I was trying to move the annotations tests to "shared", and there is apparently one test that always fails for annotations on `cloud-e2e-firefox`, ref: [test runs associated with this PR](https://app.circleci.com/pipelines/github/influxdata/ui/5514/workflows/ec2c6b95-7346-4edd-a5fb-cb017ab5b9cf/jobs/40472)

The `cloud-e2e-firefox` job should be updated to run tests from the "cloud" folder as well: https://github.com/influxdata/monitor-ci/blob/8dca13a25986dfc438650d39ef429d1b4be6b52e/.circleci/config.yml#L264

In order to do this, the failing annotations test on `cloud-e2e-firefox` will need to be resolved.

**Comment by genehynson** [comment]
sorry didn't mean to close this.

While I did manage to fix the annotations test, there are actually a[ lot of test failures](https://app.circleci.com/pipelines/github/influxdata/monitor-ci/2473/workflows/d670b3b0-c0b2-4e42-ac8b-3f9b26d0178e/jobs/21732/artifacts) when we run the cloud tests against firefox. The reason being that the firefox tests are using monitor-ci currently which is not being kept up to date with the latest services (e.g. notebooksd, quartz-mock) since it is slowly being deprecated. 

So I think what really needs to happen is 1) we find a way to get these tests to pass in monitor-ci or 2) we port the cloud-e2e-firefox job to k8s-idpe or 3) we wait until we bring remocal to our CI at which point it will be much easier to run the tests against k8s-idpe and any browser.

I'm going to spend a little bit of time seeing how hard it might be to port the cloud-e2e-firefox job to k8s-idpe in its current state. If it's easy, we can go with that. Otherwise we'll wait for remocal.

**Comment by genehynson** [comment]
Yeah so it looks like running k8s-idpe with firefox just isn't a good idea. It runs slower and will slow down the pipeline overall. And it also looks like there are a some bugs we'd have to work through. I'm going to suggest we wait for remocal integration into our CI before working on this anymore.
