### ISSUE TITLE
Bug: Dashboard UTC/Local toggle should not change the time range.

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#1830]
# Summary

When using a Custom Time Range, switching between `Local` and `UTC` timezones changes the absolute time range displayed. It should only change the timezone; the start and stop times should not change. If you have a relative time like last `1hr` and change the timezone button, the displayed times simply update to reflect the new timezone. For custom time ranges, the whole cell reloads. It should do the same as the relative time ranges.

![custom time range tz](https://user-images.githubusercontent.com/13472206/123679788-c4e4ee00-d7fc-11eb-8654-7f54e2b77156.gif)

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Create a dashboard with at least one cell returning data from a valid query.
2. Observe the dashboard is set to `Local` (default) or `UTC` timezone.
3. Select a `Custom Time Range` that returns data (see also https://github.com/influxdata/ui/issues/1827)
4. Observe the times displayed in the cell for your time range.
5. Select the other timezone (Local -> UTC or UTC -> Local)
6. Observe that the cell reloads as the absolute time range for start and stop has been modified.

**Expected behavior:**
Changing the displayed timezone should not change the absolute start and stop times. The "units" should just be updated.

**Actual behavior:**
See above: Cells reload with new start and stop times when changing the displayed timezone.

**Environment info:**
influx cloud2

**Comment by Asalem1** [comment]
This behavior is intended based on previous product discussions. Here's the original PR:

https://github.com/influxdata/influxdb/pull/18011

with the original issue being:

https://github.com/influxdata/influxdb/issues/17877

The thought process here is that if a user selects a custom time range for UTC, the selected custom time range should reflect the UTC times for the selected timerange. 

I defer to @russorat as to what the product specs should be here since the two schools of thought run contrary to one another

**Comment by russorat** [comment]
i'm reopening this because it highlights a valid edge case IMO.

in summary: 
the expectation is that changing between local/UTC in the UI only impacts the display of data, not querying of data. this is true when using relative times.

When using custom time range, switching between local/UTC reruns the query with different times, which is unexpected to the user.

The expected behavior is that the data remains the same, the display of time in the UI is updated to represent the new time. For example, the display of the custom time range in the dashboard would switch from UTC to local, but the times sent in the query wouldn't change.
