### ISSUE TITLE
React Memory Leak: SubmitQueryButton

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#1853]
### Background
Fix the memory leak in `SubmitQueryButton`

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SubmitQueryButton (created by ConnectFunction)
    in ConnectFunction (created by TimeMachineQueries)
    in div (created by FlexBox)
    in FlexBox (created by FlexBox)
    in FlexBox (created by TimeMachineQueries)
    in div (created by TimeMachineQueries)
    in div (created by TimeMachineQueries)
```

### Steps to reproduce
1. Create a cell in a dashboard
1. Edit the cell
1. Click `Submit` then immediately click the Green Check mark that saves the cell. Click this while the query is running.
1. The warning should fire in the console

**Comment by subirjolly** [comment]
Before Issue
![Before.gif](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/a21b305d-ea43-4a38-aebb-c3883fe070e7)

After Issue
![After.gif](https://images.zenhubusercontent.com/5fa9843597598f467dccb2b9/2ed33062-d779-4048-bda7-d8482b8380b3)

Just noticed that there's still a bigger issue lingering around. It's in prod and I am going to create a new issue for that. The issue is that once you click on `Submit` and then click on `Green Check`, you get sent back to the dashboard page and the cell you just edited just keeps on loading.

**Comment by subirjolly** [comment]
@hoorayimhelping I have created another "immediate" followup story: #1935
