### ISSUE TITLE
Dynamic Homepage - Usage Limits Panel On Homepage

### ISSUE THREAD

**Issue by ShmuelLotman** [influxdata/ui#1896]
_Fulfills portion of epic #1895 - Dynamic Homepage_

** Usage Panel **
     * The intent of this effort is to create a usage panel on the user's homepage that displays the user's specific usage rates, as well as the limits under their current plan

   * **Involved Effort**
     * This will primarily consist of two areas: determining the correct API to query the usage information from, and implementing the UI component itself. 

  * **Intended Outcome** 
   * A usage panel that displays user usage information and drives users to heightened awareness of their limits, and, indirectly, greater conversion rates to increase limits. 

Relevant Mock:
(link: https://www.figma.com/file/GT5UFaojilawBM5vgLf3na/Homepage-2021?node-id=0%3A1)
 ![Screen Shot 2021-07-06 at 9.47.56 AM.png](https://images.zenhubusercontent.com/5fb40d76d06a0679e8842aa1/977e572d-c20a-4587-b578-2e813fe49368)

**Comment by ShmuelLotman** [comment]
This is currently blocked by the lack of an endpoint providing us with counts for static assets that a user currently has. I'm currently in communication with @aanthony1243 on getting such an endpoint put out there so we can utilize it in building out this component without having to actually get all of the resources and then do a count on them. In the meantime, a placeholder component behind a feature flag is in PR currently and will be merged shortly.

**Comment by barbaranelson** [comment]
We have been discussing changing the free tier limits so that they actually limit customers in useful ways - e.g. the current dashboard limit isn't a real limit, as the user can just put more cells in one dashboard. Similarly limiting the number of buckets just encourages free users to write more data into fewer buckets.  We should revisit this proposed UI when we have settled on the new free tier limits, which will be more around service protection (e.g. frequency at which tasks can run).

**Comment by jzahnd** [comment]
I have made a note to follow up with a new epic or story on this based on updated limits.
