### ISSUE TITLE
The shared/annotations test is flaky in e2e

### ISSUE THREAD

**Issue by wojciechka** [influxdata/ui#1945]
The `shared/annotations` test is flaky and its success rate in E2E tests on `master` branch (which should only include stable code) for last 7 days is 89%.

**Comment by wojciechka** [comment]
Sample run:

https://app.circleci.com/pipelines/github/influxdata/idpe/17835/workflows/664ba9dc-6548-48a0-9cc7-5772d8719d69/jobs/494090

**Comment by genehynson** [comment]
FYI for whoever looks into this, it looks like there is a CSS bug causing the legend to hover above the popup and cypress is unable to click the "Save Annotation" button because it's hidden.
![image](https://user-images.githubusercontent.com/6411855/124956710-1a738480-dfcd-11eb-8bb3-ae0dcaa562ca.png)

**Comment by genehynson** [comment]
This test seems to be failing 90% of the time: `can create an annotation that is scoped to a dashboard cell`

**Comment by mkmik** [comment]
happened again today https://app.circleci.com/pipelines/github/influxdata/idpe/18058/workflows/5c50b6d8-f815-4c3c-b835-a2cd12ae5274/jobs/511571
