### ISSUE TITLE
Notebooks: I can create a notification endpoint from the alert panel

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#2282]
We would like to add the ability to create an endpoint from the alert panel.

![Screen Shot 2021-08-09 at 11.15.47 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/754c2ca0-8c88-419f-bc1b-e4cb6cb8ab38)

![Screen Shot 2021-08-09 at 11.20.44 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/f05a1956-c258-4f67-8a1e-5dd25e485f53)

![Screen Shot 2021-08-09 at 11.20.55 AM.png](https://images.zenhubusercontent.com/6058abb75f3c06c1d25467ae/dbec4c18-4275-4f77-b063-8a60f80e5a8e)

### Acceptance Criteria

- User can learn more about notification endpoints by clicking on the "Endpoint" link that shows prior to adding an endpoint. Link opens up [Manage notification endpoints docs page](https://docs.influxdata.com/influxdb/v2.0/monitor-alert/notification-endpoints/) in a separate tab
- User can open up a modal to create a notification endpoint 
- User can add multiple endpoints and select one to use for the alert
- User can edit the notification endpoint after adding it by clicking "Edit"
- Endpoint details are shown after creating an endpoint, but are read-only

Design: @juliajames12 

Design file: https://www.figma.com/file/a7qLfWdlUDrhab9aWIxE65/Create-an-Alert-from-Notebook?node-id=664%3A8142

**Comment by drdelambre** [comment]
since all of this information is embedded in the generated task, why do we have to create an external and linked resource (endpoints) instead of just having them enter the data in the details panel? feels like we're adding a bunch of clicks and navigation to the user flow, but why?
also what's the importance of ensuring that they can't edit the endpoint directly in the notebook panel?

this also isn't a statement of work until we have at least the existing integrations' interfaces designed

**Comment by drdelambre** [comment]
for now we're going to hold off on adding endpoints until we begin to see the need for reusability for this aspect in the system

**Comment by drdelambre** [comment]
we're working on #2377 instead, and holding off on this issue until we see a strong need for re-usability of endpoints from our users. there are some thoughts that an interface to the secrets subsystem here might serve the same goal with less impact.

**Comment by jzahnd** [comment]
Closing due to most recent changes / updates
