### ISSUE TITLE
Members page crashes

### ISSUE THREAD

**Issue by ftudino-indusys** [influxdata/ui#2647]
Hello, there seem to be errors on the members page,
when I click on `Username` or ` Role`, the whole website stops.

InfluxDB 2.0.8
Server: e91d418
Frontend: d6a1b9a

![Members _ Organization _ Test1 2021-09-17 9_40_14](https://user-images.githubusercontent.com/34894682/133785593-a79cd71f-3add-41b4-86e7-b49bf6ee1744.png)

**Comment by kristinarobinson** [comment]
@ftudino-indusys -- Can you verify that you are using OSS rather than our Cloud product?  I want to route you to the correct team.  Thanks.

**Comment by ftudino-indusys** [comment]
Yes, I am running OSS instance. Maybe it is a problem of my instance, it would be good if someone could corroborate it.
Regards!

**Comment by kristinarobinson** [comment]
@dgnorton , can you take a look?

**Comment by wbaker85** [comment]
I wasn't able to readily reproduce this. I tried with a large amount of members (~1000) and that does make the sorting operations take a noticeable amount of time, but the sort will successfully complete.

@ftudino-indusys - do you have even more users than I tested with? If you have a large enough amount of users it could just be that the sort is consuming all of the available system resources and causing the browser to hang for a long time. This list isn't paginated so it will render all of them, which isn't ideal.

Have you tried logging out/logging back in, restarting your browser etc? It seems like it might also be that a memory leak, possibly somewhere else in the UI, is taking up all of the resources that the sorting would need to complete successfully.

**Comment by wbaker85** [comment]
I'm able to use the members page alright with `yarn start` also. If you're able to build the ui and use the `--assets-path=path/to/ui/build` flag successfully it sounds like it's a problem with how your dev server is working rather than anything in the code. The dev server does take more system resources to run and I'd imagine there are many system/configuration dependent things that could be going on from the `yarn` side. 

You can log out by clicking here in the UI, that will clear your local storage and might help, although now that you have described what's going on more I doubt it will - but might be worth a try!

<img width="228" alt="image" src="https://user-images.githubusercontent.com/55118525/134381762-b808a61f-f207-49ce-a7f8-838804befcdd.png">

Other than that all I could suggest is to make sure you are using the latest version of yarn and an updated browser (I'm using firefox), and/or stick to using the `--assets-path` flag or using the built-in UI 😃.

**Comment by ftudino-indusys** [comment]
I agree, it seems to be a problem with my development server. I will continue with the development and if I find the problem I will attach the details. 😄 

Thanks for the support, I proceed to close the thread.
