### ISSUE TITLE
Remove Demo Data Feature in UI

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3061]
**Let's remove the demo data feature based on team feedback.** 

History

We either need to remove demo data altogether, or add whatever special logic is in the data explorer to notebooks.

Current state: If you go to your buckets list, and select the Website Monitoring Bucket, and have the option to go to notebooks when a bucket is selected, you get taken to the notebooks page, but the Website Monitoring Bucket isn't available in the list of buckets. If you go to data explorer, it is.

I know we do some special trick to get this bucket to show up, as it isn't owned by the org.  We either need to do the same trick in notebooks, or decide that now is the time to remove the demo data feature altogether, as we have other sample data we can use.

**Comment by drdelambre** [comment]
I'm voting for the later. supporting it adds a bunch of spaghetti logic that needs to enforce implicit ui specific rules, like that all buckets across all of your orgs must have unique names because we determine what org to query based on the bucket name referenced in the first `from` of your flux query instead of based on your user setting

@asalem1 and i were talking about how it also doesn't make sense that clicking on the bucket name opens up a notebook... or data explorer... that its a suprise the first time because of it's inconsistency with other lists in the app and that instead we should explicitly inform the user that they're creating a notebook, or opening it in data explorer, through a button on the bucket row. In that case, this would be to not add that button to a bucket that doesn't belong to you

**Comment by barbaranelson** [comment]
Hmm, not sure I would couple these two ideas. No matter how we decide to get to where you can query the contents of a bucket, it's not useful if you can't query the contents of the demo data bucket.  The only reason that the demo data bucket isn't owned by your org is so that we could minimize storage behind the scenes.  Other than that, it should behave like a normal bucket.  In any case, I'm fine with getting rid of demo data altogether. @bpalani?

**Comment by drdelambre** [comment]
per planning meeting, the action is to remove the demo data bucket concept. this will include depreciation of the service, removal of it's interfaces, and removal of all logic supporting demo data in our query logic. this will require an epic that @jzahnd will architect

**Comment by genehynson** [comment]
Code has been removed from the UI - now we just need to remove the openAPI spec and k8s-idpe references

**Comment by jzahnd** [comment]
Nick is following up with other teams on the remainder of this work.

**Comment by StacieClark** [comment]
Demo data is it's own org, correct? So that was already deleted from all the clusters?

**Comment by barbaranelson** [comment]
Correct.  Not sure if it's already fully deleted.  @tysonkamp was working on this.

**Comment by tysonkamp** [comment]
The service is gone.  We're waiting for some secrets to be cleaned up before closing [this](https://github.com/influxdata/k8s-idpe/issues/5509).
