### ISSUE TITLE
notebook: Sharing with an inactive token gives no data, but no error

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3129]
(I'm not exactly sure what the correct behavior should be, so filing the issue for discussion.)

If you create a share link, and then deactivate the token that was used to generate the link, the link still renders the notebook, but the visualization panel says 'No data returned'.  If you delete the token, you get a 404.

I think we should treat an inactive token like a deleted token and not show the shared notebook.

**Comment by jzahnd** [comment]
notebooksd should perhaps query the token status in order to handle the request

**Comment by jzahnd** [comment]
We could handle this by displaying a 401 unauthorized in the panel

**Comment by barbaranelson** [comment]
Another variation of this - adding here for discussion purposes. If you select a token that doesn't give access to the resources required, you get the same experience - no notification, but the shared notebook also shows no data - e.g. notebook queries from bucket A, but I use a token with read access to bucket B.  Not sure if there is some way to limit the tokens you can select to ones that would work with the resources referenced. Maybe for now, we let it go, and just document that if you select a token that doesn't have access (e.g. because it's referencing the wrong bucket, or it's inactive) the notebook won't render correctly.

**Comment by genehynson** [comment]
Hmm let me see how hard it would be to show a message in the visualization panel that fails like "unauthorized access" or something

**Comment by genehynson** [comment]
Ok I was able to handle that scenario by using the error message returned by the query API. In this situation I used a token that didn't have access to the `_tasks` bucket.
![image](https://user-images.githubusercontent.com/6411855/140216427-3f2a8a66-3291-43c3-a4cd-ea2b9f3d0a19.png)

**Comment by StacieClark** [comment]
Gene, token and authorization issues should return 401 no authorization errors.

**Comment by genehynson** [comment]
While I agree that in most cases a 401 is what should be returned for authorization issues, it’s important to consider the data you might be leaking by returning a different status code for specific scenarios. In this case, returning a 401 would tell a malicious actor that they have found the correct URL for a shared notebook. We decided to consistently return 404s if the notebook was not shared or if the token was inactive so that malicious actors can not tell the difference. This is a common practice - take Github for example. If you try and visit a the IDPE repo in an incognito browser, you'll get a 404 instead of a 401
