### ISSUE TITLE
Client library export instructions contain html instead of clickable links

### ISSUE THREAD

**Issue by mavarius** [influxdata/ui#3239]
## About the bug

**Steps to reproduce:**
1. Open a new notebook
2. Export query as client library code
3. Select any library
4. Open installation instructions section

**Expected behavior:**

The instructions contain a clickable link.
![image](https://user-images.githubusercontent.com/11937365/141862393-9f27eeed-f01b-489b-9e9c-f8a20bd6a4e6.png)

**Actual behavior:**

The instructions contain the HTML tag for the clickable link.
![image](https://user-images.githubusercontent.com/11937365/141861908-77552425-c84c-4d77-8d15-f11e731cdcb7.png)

**Comment by TCL735** [comment]
This is difficult to do without resorting to something like React's `dangerouslySetInnerHTML` because

- UI code is loading the markdown dynamically at run-time which causes links to be subject to sanitization by React
- In other places where markdown links are rendered correctly, the markdown is loaded at compile time

**Comment by TCL735** [comment]
The other option would be to not load the markdown here dynamically. This will require a refactor of the code.

**Comment by TCL735** [comment]
Another option would be to use the `[link](url)` style of linking in the markdown and then add a `linkTarget` property to the props of `<ReactMarkdown>`

But this option does not have a way to add **"noopener"** and **"noreferrer"**

**Comment by jzahnd** [comment]
Check with @ivankudibal if this is a UI task or not.

**Comment by ivankudibal** [comment]
if there is no side effect, I would prefer latest solution https://github.com/influxdata/ui/issues/3239#issuecomment-969601691 , then the description.md files could be rewritten to pure markdown syntax

**Comment by appletreeisyellow** [comment]
This is fixed in #3546 by rewriting the description.md files in pure markdown syntax. 

As mentioned in [#3239 (Comment)](https://github.com/influxdata/ui/issues/3239#issuecomment-969601691), this fix doesn't support "noreferrer noopener" keyword as `<ReactMarkdown>` doesn't support `rel` attribute currently.
