### ISSUE TITLE
notebook sharing: maps don't render correctly in a shared notebook

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3245]
If you share a notebook with a map, the map will not display and you get the error "we are having issues connecting to the Maps Server. Please try again later". The request GET https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/maps/mapToken fails with a 401.

Note when trying to reproduce - For some users the notebook will render correctly, if they happen to have the maps token in their session cookie.  Need to test in an incognito window.

**Comment by genehynson** [comment]
The reason this happens is because the `mapsd` service that provides this token lives behind gateway and therefore requires a JWT to use it. Users visiting a shared notebook will not have a JWT and therefore this fails. Probably the best work around to this is to have a maps token returned with the notebook spec from notebooksd. So basically notebooksd will ask mapsd for the map token using the stored API token.

**Comment by barbaranelson** [comment]
As a short-term workaround, can we pop up a warning when someone tries to share a notebook with a map to let them know that the map will not render?

**Comment by genehynson** [comment]
We could - but I don't think fixing this would be all that difficult. I'd probably point it a 2. So my vote would be to just fix the problem

**Comment by barbaranelson** [comment]
If we can fix it before the compute team delivers the centralized service to get a JWT, then I agree.  Much better to fix it than to put up a warning. If we have to wait until the compute team delivers the new service, that might be a longer time delay so we might need the warning.

**Comment by genehynson** [comment]
Gotcha. Yes, we can just use the stored API token to make the request to mapsd while we're waiting on the centralized JWT service from the compute team

**Comment by asalem1** [comment]
Moving this to blocked until I can get a maps token to be returned in remocal
