### ISSUE TITLE
Epic: Handle default timeframes for graphs in Data Explorer, Dashboards, and Notebooks

### ISSUE THREAD

**Issue by kristinarobinson** [influxdata/ui#3307]
When using specific time ranges in flux (versus the variable v.startTime and v.endTime), change the x axis in all graphs types to automatically use the start and end times of the of the flux query.

Add an indicator when NOT referring to the dropdown values (v.startTime and v.endTime) on any Dashboard cell.

If the flux refers to the variables of the dropdown, then by default the range of the graph should be the entire range of the dropdown.

**Comment by philjb** [comment]
Love this improvement idea; For me, and I think this applies to nearly all data I look at (I can't think of a counter example), I always want a time based x-axis to be the width of the time range I requested. If I asked the range to be 3 hours wide (dropdown, explicit start/stop, relative, variable, computed, etc), I want 3 hours of x-axis. Since there is no x-axis domain control in our gui, auto defaulting to the width of the data returned is quite surprising to me as the end user.

**Comment by wiedld** [comment]
Already done.
