### ISSUE TITLE
Notebooks: Add ability to download presentation mode as PDF/PNG

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3325]
Currently, our exports as referenced in #3273 just take a screenshot of the page for Notebooks. We would like to provide an export view that is in presentation mode. It likely makes most sense to start this off with a PDF and Image view for sharing for users that customers cannot or do not want to add to their org access. 

Design: 
[Figma](https://www.figma.com/file/OEeEqe0M7eOr8r87CuXfFD/Download-PDF%2FImage-Presentation?node-id=26%3A1085)

Edit Mode
<img width="1919" alt="Notebook Edit Mode (4)" src="https://user-images.githubusercontent.com/81173353/148818020-cf0db290-770a-4733-aaf7-993e8778b773.png">

Presentation Mode
<img width="1911" alt="Notebook Presentation Mode (1)" src="https://user-images.githubusercontent.com/81173353/148818113-d5dff611-e9e2-4fdc-acb9-eea65c0bbb3b.png">

**Comment by appletreeisyellow** [comment]
When a notebook is long and the PDF version of the notebook is more than one page, here is an example of what we have for now:

<img width="1493" alt="Screen Shot 2022-01-14 at 8 59 05 AM" src="https://user-images.githubusercontent.com/14298407/149540366-d2e96a52-dac1-4f5b-b017-00d2a11a6c9c.png">

Do we want to keep this way? Or do we want to keep each cell complete by splitting the pipe list into pieces and place each complete cell on a new page?

I would prefer the first option. 

With the second option, we have two things to consider:
1. We need to do some research and change tools for PDF downloading because of the limitation of the tools we are currently using. We are now using two third-party tools `html2canvas` and `jspdf` to build the functionality for PDF downloading. `html2canvas` takes one screenshot of the entire pipe list and `jspdf` splits the screenshot into different PDF pages. `html2canvas` currently doesn't support taking multiple screenshots for each pipe cell, so if we want to do the second options, we might need to change to other tools.
2. If a pipe cell is long and takes up more than one page, e.g. a long flux script cell, we may fall back to the situation of option 1 where the cell is being cut.

**Comment by appletreeisyellow** [comment]
Here is an example of the current downloaded PNG file. There are two elements missing: 1) InfluxData logo, and 2) title of the notebook. 

![Unity Notebook Test (1)](https://user-images.githubusercontent.com/14298407/149976720-b1836497-e3e9-4b7c-a89d-1aaa9cc5ef89.png)

The current PNG download functionality is able to download whatever area we want to select. However, the limitation is that, we cannot add elements or remove elements within this area. 

I'm going to do more research to see if there is any third party tool similar to `jspdf` but is for `png`.

**Comment by garylfowler** [comment]
My thought would be to push as is for now.  If user is downloading as image (versus data export), the precise data may not be essential as it will likely just be a representation of a larger picture.  I don't have great context on what users are using this feature for, so that is a bit of an uninformed opinion.  But we could then look and see how often the feature gets used before we prioritize the research of an alternate tool/method over other work.  Just my initial .02

**Comment by jzahnd** [comment]
We are all good to ship this as is. We can follow up on our design concerns if enough users interact with downloading in PDF.
