### ISSUE TITLE
Replace client.telegrafConfigs

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#3384]
Related to #2902

Similar to #3383 

This issue might be a bit more intense than #3383 since it's poorly scoped and may contain a lot of gotchas, especially with regard to typescript and OpenAPI. The gist of this is that we want to audit the `client.telegrafConfigs` usage and replace all existing usages of it with generated functions. The purpose of this is to limit our usage of the client library so that we can slowly transition away from it as a dependency (as best we can under the current constraints of the build system).

This issue might require a bit more work to integrate full, but we basically want to try:

- [x] Identify all usages of `client.telegrafConfigs.*`
- [x] Replace `client.telegrafConfigs.*` with existing generated endpoints
- [x] Identify any gaps between what we are currently generating, and what we are using with the client library
- [x] Update OpenAPI yaml definitions to bridge the gap between those
- [x] Replace any types related to the `client.telegrafConfigs` with the generated types

**Comment by appletreeisyellow** [comment]
Currently there are two files are using `client.telegrafConfigs.*`. Most of the dependencies can be replaced by the generated functions, expect three:

1. `client.telegrafConfigs.get` in the file `src/telegrafs/actions/thunks.ts`
2. `client.telegrafConfigs.create` in the file `src/dataLoaders/actions/dataLoaders`
3. `client.telegrafConfigs.update` in the file `src/dataLoaders/actions/dataLoaders`

We might want to update OpenAPI to resolve the following issues:

1. `getTelegraf` function from the auto generated api in `src/client` file returns a string instead of an object. It might be an issue in `GET /telegrafs/{telegrafID}` on OpenAPI
2. `postTelegraf` function from the auto generated api does not include `plugins`. We might want to add `plugins` to the request body of `POST /telegrafs/{telegrafID}` and `PUT /telegrafs/{telegrafID}`
