### ISSUE TITLE
Notebooks: Updates to Share and Download PNG/PDF Notebook pages

### ISSUE THREAD

**Issue by juliajames12** [influxdata/ui#3408]
We'd like to create a consistent look and feel between the share and download png/pdf pages and clean up the spacing/padding. 

Check out the design file below for exact pixels for spacing/padding. 

Figma: https://www.figma.com/file/mzSPO5PkrnlCneB6ARygI2/Share%2FDownload-View?node-id=0%3A1

**Comment by appletreeisyellow** [comment]
There are two new designs in this Figma link. The first one is a quick fix on margin, fixed by PR #3502. The second new design is considered as part of issue #3325, so we might want to have a separate PR to meet the need. 

The reason why the second design is part of issue #3225 is that, downloading Notebooks in PDF does not require a new page. The PDF/PNG is generated on the current page. Once the design of downloading button is finalized, we can move forward with the implementation.
