### ISSUE TITLE
Builtin variable `v` is marked as undefined by the flux language parser 

### ISSUE THREAD

**Issue by philjb** [influxdata/ui#3427]
## About the bug

This looks like minor fall out from the new flux LSP update: https://github.com/influxdata/ui/pull/2712

The variable `v` such as used for `v.windowStart`, `v.windowPeriod` etc is flagged in the editing window as "undefined", but the queries run just fine. see screenshot

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. write a flux query containing e.g. `range(start: v.timeRangeStart, stop: v.timeRangeStop)` in the cloud 2 flux editor window
2. note that the `v` variables have the red underlying and the tooltip says "undefined".

**Expected behavior:**
There is not a language/syntax error shown

**Actual behavior:**
See screenshot.

**Visual Proof:**

<img width="716" alt="Screen Shot 2021-12-13 at 4 59 20 PM" src="https://user-images.githubusercontent.com/13472206/145914110-ffec7ceb-c1c4-4a1f-9728-279441713a78.png">

## About your environment
cloud2
**Environment info:**

**Config:**
na

**Logs:**
na

**Performance:**
na

**Comment by nathanielc** [comment]
This is likely because the LSP isn't being told about the definition of `v` that the UI injects into the editor before running queries. A simple fix would be to prepend the text to the editor contents before sending it to the LSP. However that will mess up position information as the contents being edited are not the same as what the LSP sees.

A proper way to solve this would be to send the contents of the `v` option as a separate file to the LSP and teach the LSP how to manage multi file packages. The LSP has the skeleton in place to handle multiple files but it is not implemented yet. 

@rockstar Thoughts? 

In either case this will take some coordination between both the UI and LSP side of things.

**Comment by jzahnd** [comment]
Jessica will follow up with Flux team

**Comment by rockstar** [comment]
> A proper way to solve this would be to send the contents of the v option as a separate file to the LSP and teach the LSP how to manage multi file packages. The LSP has the skeleton in place to handle multiple files but it is not implemented yet.

This would probably not be a trivial amount of work, but after talking with @nathanielc, it's work that we'll need to do in the future anyway. Every other solution we can come up with is a hack that (a) has all kinds of downsides, and (b) will have to be removed when we do this work anyway, so I think it'd just be good to prioritize this work in the next few sprints and make this option work.

**Comment by jzahnd** [comment]
@rockstar That sounds awesome, we appreciate it! We will keep an eye on the work as it moves forward and will plan some time to be available to test as it moves forward.

**Comment by nathanielc** [comment]
The LSP support landed this week https://github.com/influxdata/flux-lsp/issues/405 :tada:
