### ISSUE TITLE
Bug: Notebooks Color Thresholds unusuable

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#3529]
### Problem

The issue here is that the color threshold on a notebook panel needs work. In it's current state I have to click on the input field to set the input, and hit command + a to select the entire input, then type the threshold in without actually seeing what i'm typing, then hitting the return key to have those changes reflected.

### What a solution would look like

Team up with design for a better solution than the current one. There isn't much room in that sidebar to interact with the input field, hence the original issue. 

![color-thresholds](https://user-images.githubusercontent.com/19984220/148548199-07fff958-f67a-4a2d-8c85-077ec5a78f29.gif)

**Comment by drdelambre** [comment]
as a first pass while design works on a better solution (moving the sidebar to a popover style drawer, having the visualization options scale better, etc), since we built all of these components originally for DE, lets make the notebooks sidebar the same width as the drawer that pops up in DE for editing view options. this should buy us some time to let design work through it

**Comment by asalem1** [comment]
For reference, the sidebar size has been bumped but some of the issues still persist

**Comment by juliajames12** [comment]
@jzahnd Going to work on this ticket this week. Spoke with Ari about the main issue, which can be seen once you turn on the feature flag 'flowErrorThresholds' and try to use the between threshold option.

**Comment by juliajames12** [comment]
@jzahnd Here is my proposal for a new design. The colorized threshold issues were fixed with the increase in the panel width, but we still had an issue with the error thresholds. 

Before:
<img width="431" alt="Error Thresholds - Before" src="https://user-images.githubusercontent.com/81173353/152851527-1f1b0375-fbb9-412d-98a7-2efa6e4cad92.png">

After:
<img width="398" alt="Error Thresholds - After" src="https://user-images.githubusercontent.com/81173353/152851548-0a95000b-94e8-410d-9b75-df29fd58b8c6.png">

**Comment by jzahnd** [comment]
Closing this ticket as we are now addressing error thresholds in #3797
