### ISSUE TITLE
Spike: Implement import/export dashboards using pkgr

### ISSUE THREAD

**Issue by barbaranelson** [influxdata/ui#3552]
In the UI, we have supported two different capabilities that we call templates. One is the V2 templates (community templates) and the other is V1 templates (specific to the UI). We want to remove all V1 template code, as it is confusing to users and developers.

As part of this spike, assess how hard it would be to hook the existing UI (for import/export of dashboards) to the pkgr, so that we can generate templates in v2 format.

**Comment by hoorayimhelping** [comment]
This is possible. I whipped up a little proof of concept, here it is in action

https://user-images.githubusercontent.com/146112/152873868-304ace55-e1e5-4251-b0c2-15df91c90709.mov

**Comment by hoorayimhelping** [comment]
Some thoughts:

These templates will be a different format. There may be some confusion among users who are using legacy templates as those won't work anymore. Because of this, users will have to re-export any dashboards they want to be able to import elsewhere

I tested this with the new system for a few simple cases. Complex dashboards with lots of variables may not work as well as simple ones. There might be some follow-up work to handle these cases.

**Comment by hoorayimhelping** [comment]
Created an issue to track this work specifically: #3414 3802
