### ISSUE TITLE
Notebooks: Make Notebooks Sidebar the Same Width as Data Explorer Drawer

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3632]
We are having some issues interacting with elements in the Notebooks sidebar where spacing is too cramped (see #3529). For now, we would like to apply the same width to the Notebooks sidebar as we have on the Data Explorer pop-out drawer, while we work through a larger design approach for handling the notebooks sidebar in a more intuitive manner. 

## Acceptance Criteria
- Notebooks sidebar is the same width as Data Explorer

**Comment by asalem1** [comment]
I'm pretty sure that it's since been updated to be the same width, but that we should explore a redesign since we're going to need to widen the sidebar to account for upcoming configurations on visualizations that will require the user to make more selections that are currently constrained by the width

**Comment by drdelambre** [comment]
given that info, lets close this in favor for the original ticket as a place to capture the redesign work
