### ISSUE TITLE
Templates: Removal of the template from UI should not remove the bucket and my data in cloud2

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/ui#3715]
## About the bug

Templates: Removal of the template from UI should not remove the bucket and my data in cloud2

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Apply work around #3714,  create empty cloud account and apply the iot_center template
2. Then write the data
3. Display the dashboard, then click on Install template and remove the `iot_center`
4. Confirm deleting resources

**Expected behavior:**

The dashboard should be removed, not my data.

**Actual behavior:**

The bucket with data is lost.

**Visual Proof:**

## About your environment

**Environment info:**

Cloud2

**Comment by barbaranelson** [comment]
This is not a bug, and is by design.  If you install a template with a collection of resources (e.g. bucket, dashboard, label), and then you delete the template, it deletes the resources that it created. If you don't want the bucket deleted when the template is deleted, then you should not include the bucket in the template.
