### ISSUE TITLE
Switching from graph to band caused an error

### ISSUE THREAD

**Issue by deejiw** [influxdata/ui#3763]
## About the bug

**Steps to reproduce:**
1. Open http://localhost:8086
2. Open dashboard
3. Edit one graph and change it to band

**Expected behavior:**
See the band

**Actual behavior:**
An error has occurred

**Visual Proof:**
![image](https://user-images.githubusercontent.com/30390987/152125834-8df5b7a4-bcbb-4ecd-91f4-83f2e021fecf.png)

## About your environment

**Environment info:**

**Config:**
Everything is default

**Logs:**
ts=2022-02-02T08:36:20.108579Z lvl=info msg="Cache snapshot (end)" log_id=0ZQ5Lcnl000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot op_event=end op_elapsed=40.215ms
ts=2022-02-02T08:59:41.139681Z lvl=info msg="Retention policy deletion check (start)" log_id=0ZQ5Lcnl000 service=retention op_name=retention_delete_check op_event=start
ts=2022-02-02T08:59:41.139780Z lvl=info msg="Retention policy deletion check (end)" log_id=0ZQ5Lcnl000 service=retention op_name=retention_delete_check op_event=end op_elapsed=0.116ms
ts=2022-02-02T09:10:04.243697Z lvl=info msg="Cache snapshot (start)" log_id=0ZQ5Lcnl000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot op_event=start
ts=2022-02-02T09:10:04.266908Z lvl=info msg="Snapshot for path written" log_id=0ZQ5Lcnl000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot path=/var/lib/influxdb2/engine/data/785dd55beb22fbd1/autogen/19 duration=23.268ms
ts=2022-02-02T09:10:04.266958Z lvl=info msg="Cache snapshot (end)" log_id=0ZQ5Lcnl000 service=storage-engine engine=tsm1 op_name=tsm1_cache_snapshot op_event=end op_elapsed=23.316ms

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

[profiles.tar.gz](https://github.com/influxdata/ui/files/7985146/profiles.tar.gz)
[vars.txt](https://github.com/influxdata/ui/files/7985148/vars.txt)
[iostat.txt](https://github.com/influxdata/ui/files/7985149/iostat.txt)

**Comment by kristinarobinson** [comment]
@deejiw In order to use the Band graph, you must select three **aggregate functions** to graph.  Just switching from graph to band will fail.

One way to correct it: click on the **Gear**, click **Configure**, then click **Customize**.  Make sure to enter the desired aggregrate function in the **Upper, Lower, and Main Column Names** under the Section labeled `Aggregate Functions`.

Here's a picture:
![image](https://user-images.githubusercontent.com/70343856/152214324-0ccdf28a-5c45-4a24-ae1c-0126e5f1e317.png)

If you are modifying a line graph and changing it to band chart, using the `Data Explorer`, and `Query Builder`, here's how to select the three aggregate functions:
![image](https://user-images.githubusercontent.com/70343856/152214744-b810ad86-96f5-427b-b5e0-b6998bddfdf8.png)

If you're modifying a line graph and changing it to band chart, using the `Data Explorer` and writing flux directly, you will need to write three yield statements, with different names and aggregate functions behind them like so:

`
from(bucket: "foo")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mymeasurement")
  |> filter(fn: (r) => r["_field"] == "myfield")
  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)
  |> yield(name: "mean")

from(bucket: "foo")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mymeasurement")
  |> filter(fn: (r) => r["_field"] == "myfield")
  |> aggregateWindow(every: 24h, fn: min, createEmpty: false)
  |> yield(name: "min")

from(bucket: "foo")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "mymeasurement")
  |> filter(fn: (r) => r["_field"] == "myfield")
  |> aggregateWindow(every: 24h, fn: max, createEmpty: false)
  |> yield(name: "max")
`

Please let me know if this does not solve your issue.
