### ISSUE TITLE
Show Flux Magic in the UI

### ISSUE THREAD

**Issue by jzahnd** [influxdata/ui#3938]
There are many areas in the UI where Flux can be created and edited where we provide some functionality that has "behind the scenes" Flux manipulation. There are several side effects to this magic such as mismatching line numbers ([#3416](https://github.com/influxdata/ui/issues/3938)) and obfuscation of some imports, updates etc of the query to make the magic work. 

We would like to address this confusion by providing a mechanism for showing users the flux modification(s). This could address several existing issues and would clarify some of the UI functionality that is handled for the user. 

**Note:** This epic is subject to change based on our Query Experience efforts. We will also likely wait for the resolution of that exploration before moving forward on this epic

## Potential Next Steps

- Support "read only" sections in the editor that show the user the system generated Flux modifications

## Related Issues

- #3416
- #3427

**Comment by wiedld** [comment]
Had an interesting conversation yesterday, about our problem with comparing a “user-facing” flux, to an under-the-cover expanded/edited flux (with more lines and/or characters added). Turns out that there is a very close analogy to macro expansion in programming languages — which is a solved problem.

.

Macro expansions work the exact same way:
1. User writes lines of code (e.g. flux)
2. Under-the-cover, additional code is injected (including new lines of code)
3. Code is compiled and run
4. Errors need to be surfaced based on the line counts/position for step 1.

.

One proposed solution, which fits in with our current approach we use in the UI codebase:
1. We parse our flux syntax to an AST. (As we already do.)
    * But this time, the parser returns both the AST…and a metadata object containing line numbers etc.
2. We make our changes. (As we already do.)
3. We stringily to flux. (As we already do.)
4. When we call the next API owned by the flux teams, we provide the metadata object.
    * e.g. the query endpoint `/api/v2/query`
5. API returns errors based on the metadata object.
    * If a metadata object was provide in the API call —> use line counts from the metadata.
    * If no metadata object exists (because UI never parsed & restringified), then when the flux engine re-parses again (which is already does) —> use that metadata object for line counts.


I believe this would not need to be a heavy lift (but would need to consult with the flux team). Because we can start with a coarse metadata object (e.g. just the original tokenization preserved)….and eventually move into a more refined/smaller object.

**Comment by drdelambre** [comment]
this isn't just about messed up line numbers. we already have a solution for what you're proposing with the extern param for the query endpoint that lets us inject arbitrary ast partials outside of the source query. that has a bunch of issues when it comes to teaching people flux and editing flux... to have magic mental models working behind the scene... which is why we're migrating away from it. the intent here is to not do any magic, but instead to allow the user to see those injections with clear indications that _we_ are the ones generating them
