### ISSUE TITLE
Bug: Tokens: Accordion should not be collapsible

### ISSUE THREAD

**Issue by Palakp41** [influxdata/ui#3974]
We want to update the design such that, the accordions are scrollable but not collapsible when `read` or `write` all is clicked.

**Comment by kristinarobinson** [comment]
It is a bug, because of the behavior of the clockface component.  When the "Read" side has specific resources checked, and the "Write" side has "All resources" check, the component collapses.  The specific Read components are no longer visible and further, not propagated correctly to the API creating the token.  The proposed change is to simply remove the collapsing function altogether when "All" resources are selected on either side.

**Comment by hoorayimhelping** [comment]
Fixed with https://github.com/influxdata/ui/pull/3835
