### ISSUE TITLE
Multi Org Phase 1 - User Profile Page

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4049]
**Multi Org - User Profile Page**

**User Story: User Profile Page**
As a user, I want a user profile page separate from account and org pages so that I can set user-specific settings such as my default org.

    **ACs**
    - The user profile page displays the user's first and last name, email address, and Default Settings including default account selection and default org selection for users' active account. 
    - Hide the account and org name dropdowns in the nav bar
    - Continue to display the user profile icon in the nav bar
    - Allow the user to update their first name and last name
    - Allow the user to set a default account via a default account dropdown
    - Allow the user to set a default org for the account they're currently in (display their current active account)
    - User clicks 'save changes' to save everything on the page. 1 save button for the whole page. 

   **Dev Notes**
        - See Figma or the image below in the comments.

**Comment by Luckette** [comment]
On hold, until we receive the new design from @juliajames12.

**Comment by juliajames12** [comment]
Here's the final design until we get user feedback.

<img width="1512" alt="User Profile" src="https://user-images.githubusercontent.com/81173353/180860149-403fb834-2b73-4d62-8b5c-3d0b5f343d4e.png">

https://www.figma.com/file/fvVSKwnepmRWvzFlIxCWCe/Multi-org?node-id=1598%3A10855

**Comment by wdoconnell** [comment]
Just discussed at multi-org checkin: 

1. user profile page will not hide the globalHeader, as we are now only displaying one account at a time.
2. ability to change user first name and last name is phase 2 rather than phase 1 - this requires a new endpoint.
3. simplify notifications to just say something more basic like 'Saved user preferences.' or 'Unable to save user preferences.'

@juliajames12 @Luckette @eatondustin1

**Comment by eatondustin1** [comment]
> 2. ability to change user first name and last name is phase 2 rather than phase 1 - this requires a new endpoint.

@wdoconnell Same with the email if I'm not mistaken, but that all sounds right to me.

**Comment by wdoconnell** [comment]
@eatondustin1 Right -  I sensed concern though with bundling email into the same ticket, both because it requires more confirmation steps than just changing name (e.g., need a confirmation email), and also security considerations (e.g., maybe user shouldn't be allowed to switch to an email on a different domain; maybe it needs confirmation from another approval, etc.).

**Comment by eatondustin1** [comment]
Ah that makes sense, I just didn't know if you left it out of your comment because you were thinking it was still part of Phase 1. So just a misunderstanding, all good!
