### ISSUE TITLE
Pinned Item still appears even if item has been deleted

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#4062]
1) Create a notebook
2) Pin that notebook
3) Go to home and observe it on the main page
4) Go back into notebooks and delete that notebook
5) Go back to home page; pinned entry still exists
6) Try to access that notebook; you receive an error that it doesn't exist

An argument could be made that this is the best & proper behavior. but I think we should consider removing any *pinnage* prior to deleting a notebook.

**Comment by juliajames12** [comment]
@garylfowler I think users would expect the notebook to be removed from both the Notebook list page and pinned items page after deleting. I think the current experience is confusing and would seem like a bug to users. But I think it would be good to warn users that they are deleting a pinned item, especially since pinned items probably hold some extra importance to the user. 

This would be my recommended user flow:
1. User clicks to delete a notebook that's pinned
2. They see a modal stating they are deleting a pinned notebook - are they sure they want to delete
3. User confirms they want to delete it, and it's removed from the pinned items 
OR
3. User realizes this is an important notebook and they decide not to delete by selecting cancel

If we're good with this approach and this is possible from an engineering perspective, I can design what that confirmation modal would look like.

**Comment by garylfowler** [comment]
@juliajames12 - Yes, I agree with the approach - thank you!

**Comment by garylfowler** [comment]
This is no longer reproducible for me, either.  I think we can close for now.  I don't know why it is no longer happening, but definitely did last week.
