### ISSUE TITLE
Performance: Iterating across published versions can be slow

### ISSUE THREAD

**Issue by asalem1** [influxdata/ui#4283]
In cases where a lot of data is being queried, iterating through the published versions of a notebook can be slow. We should we what we can do to make the experience a bit more responsive and quick

**Comment by subirjolly** [comment]
I'd like to start identifying the performance issues I am seeing and things I have worked on. Those fixes might be removed, if we think they aren't as useful or needed.

**Performance Issues**
1. Version List Delay - Fixed by Caching - Not needed(Per Review)
**Before** 
![image](https://user-images.githubusercontent.com/1637395/165550913-daba7c96-4334-4715-a356-1244b3d9d294.png)
**After**
![image](https://user-images.githubusercontent.com/1637395/165551021-a3a6cd2d-73f8-4cc9-b748-2136d6690e4a.png)

2. Ability to cancel queries. What I understood was that when we are moving away from one version to another or from a version back to the notebook, the longer running or high data fetching queries might make browser a little unstable. So, I added the cancellation of queries when we interact with other version(s) or go back to notebook.

I am still trying to identify performance issues. Will update this issue when I encounter more cases.

**Comment by subirjolly** [comment]
https://github.com/influxdata/ui/pull/4504 - Closed PR - No need for this.
https://github.com/influxdata/ui/pull/4505 - Merged.

**Comment by subirjolly** [comment]
**Performance Issue #: 3**
I have noticed that the entire UI gets stalls or hangs when a big query is running. It does periodically give control back to the mouse/browser and other components but the entire tab and mouse seems to be stuck in a particular state.

I am trying to figure out if it's possible to keep the processing localized to the components making calls.

**Comment by subirjolly** [comment]
@asalem1 has tackled the `fromFlux` issue. The performance looks a lot better. There's still some hang which is happening because of the 2nd slower area(`for` loop), specifically `csvParse` to an extent.

**Comment by asalem1** [comment]
Closing this since it's being addressed with performance enhancements on the fromFlux parser in giraffe
