### ISSUE TITLE
RedirectTo URL should be hashed

### ISSUE THREAD

**Issue by Asalem1** [influxdata/ui#429]
This is a `2` because of feature flagging and coordinating the changes with the API

### Problem

The current redirectTo logic when a user logs in explicitly sets the redirect URL in the URL params. This URL isn't hashed. It might pose some security concerns (and length issues in a URL).

### Solution

Hash & parse the URL when it's set and gotten

**Comment by kristinarobinson** [comment]
Ari - shortening the URL via hashing does NOT provide any security strengthening, fyi.

**Comment by randycoulman** [comment]
Quartz handles this by putting the original URL into the session, and then reading it from the session to redirect the user once they're logged in.

Given that we're moving to a shared session cookie, we could adopt this same approach system-wide and I think that would resolve the security issues here.

**Comment by Asalem1** [comment]
Perfect. Ya that's currently how the UI handles it for cloud but I wasn't sure if there was a potentially better way

**Comment by gunnaraasen** [comment]
We do have an open security issue (https://github.com/influxdata/quartz/issues/3299, https://github.com/influxdata/quartz/issues/3298) due to a lack of validation on the redirect URL.

I would vote to go with Randy's suggestion and document a system-wide redirect approach. I am concerned that hashing the redirect URL might require communication between quartz and IDPE to resolve the hash back into the URL. Alternatively, we could always tag one system as the place to resolve the redirect.

**Comment by randycoulman** [comment]
@gunnaraasen Both of those issues seem like they're on the IDPE login flow, not Quartz. Does that sound right?

**Comment by gunnaraasen** [comment]
Good point, I didn't notice the IDPE URL in the issue. Though it seems likely that quartz is also susceptible to the same attack unless you think we're already validating redirect URLs.

**Comment by randycoulman** [comment]
For influxdata/quartz#3299, Quartz doesn't put a `redirectTo` URL in the URL params, so it is not susceptible to that issue. We probably need to do something with influxdata/quartz#3298, though, because I don't think Quartz sets that state field either.

We're digressing from the point of this issue, though, so we should move this discussion to those issues instead.

**Comment by Asalem1** [comment]
I'm gonna close this in favor of the URL validation that Gunnar linked above:

https://github.com/influxdata/quartz/issues/3299
