### ISSUE TITLE
250 Credit: End to End Testing

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4314]

**Comment by TCL735** [comment]
e2e tests are not possible in the UI using Cypress for Google Optimize experiments as they are not supported by Cypress. Or at least not without a lot of extra work. No such examples of e2e tests exist from previous experiments. As such, we will do manual testing rather than automated e2e tests.

Additionally, some unit tests were added as part of https://github.com/influxdata/ui/pull/4600
