### ISSUE TITLE
flaky test: shared/dashboardsView

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#4403]
cypress/e2e/shared/dashboardsView.test.ts has become very slow. This slowness will fail the test, even if the test has a green checkmark.

![image](https://user-images.githubusercontent.com/10736577/163292430-963bc546-f0dd-4b6d-a7d3-f149cb409ab2.png)

Here is a pipeline with 20x runs showing multiple failures for Firefox: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/10855/workflows/6e50ca9a-f349-45dd-842a-597e9d5606cd

**Comment by wiedld** [comment]
Unsure if this test is flaky due to the usual problem (of not finding a DOM element), or because the test is squeaking over the threshold of a timeout.

Here is some data gathered:
```
10851 --> first time we see the total length of time on this test was 20min etc.

but earlier tests would have single runs of the tests, which did potentially error due to timeout:
10845 --> firefox failed with timeout. 6min
10843 --> both passed first time with 5min
10842 & 10841 --> both passed first time with 4min
10840 --> chrome passes 4min. firefox timeout 6min.
10833 --> chrome passes 5min. firefox passes 6min.

from yesterday:
10786 -- both passed first time with 5min.
10785 -- both passed first time with 4min.
```

**Comment by genehynson** [comment]
Some more info: I opened a PR that isolates the test that is "failing" here: https://github.com/influxdata/ui/pull/4405 And here's the corresponding monitor-ci run for that PR: https://app.circleci.com/pipelines/github/influxdata/monitor-ci/10861/workflows/abe386f5-9690-49f0-b720-e3fc9178adf4

Notice that the dashboardView test suite now passes 20/20 runs. The new test suite I added with the single test, dashboardViewBadTest, passes 15/20 runs (all failures are from firefox). Unfortunately all the failures don't seem to have video artifacts - potential bug in cypress or firefox? Most likely a red herring. 

So I think two things should be done:
1) split the dashboardView test into two test suites because it's too damn long <insert gif here> :P 
2) try and reproduce the failure with the `can create, clone and destroy cells & toggle in and out of presentation mode` with firefox locally and resolve it - I think it's just flaky?
