### ISSUE TITLE
reduce code duplication when creating graph configurations

### ISSUE THREAD

**Issue by jrenee42** [influxdata/ui#453]
for ui/src/views/helpers/index.ts:

   there is a lot of code duplication when creating the properties.

so:  refactor out duplication and write unit tests alongside them.

question:  why do we need all these null properties?  empty arrays and properties with default values are understandable, but do we need all these empty/null properties?

partnered with @joelfried

**Comment by drdelambre** [comment]
@jrenee42 the problem goes deeper than just this file. we can't build a lot of automation around the giraffe interfaces to idpe because each of these types is created piecemeal. look at the definition of an x axes label for `xy` views vs `histogram` views. it would be awesome if you could figure out a way to define some primatives for these types and propagate that back to the api.

**Comment by jrenee42** [comment]
@drdelambre  agreed there's lots of duplication.  let's talk about this tomorrow...what a better implementation would look like.
