### ISSUE TITLE
Bug: Dashboard - "Need more dashboards" covered by "GET MORE DASHBOARDS"

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4596]
"Need more dashboards" covered by "GET MORE DASHBOARDS"

![Image](https://user-images.githubusercontent.com/98195941/168848559-6f67a184-98c6-4b56-a9af-e3e30a4fa63e.png)

**Comment by TCL735** [comment]
This appears to only happen when the Upgrade is the first Card of a row.

**Comment by TCL735** [comment]
This is the culprit: https://github.com/influxdata/ui/blob/master/src/dashboards/components/DashboardsCardGrid.scss#L20-L28

The grid CSS sets the height of all elements in a row based on the height of the first element in that row.

When the `AssetLimitAlert` card with the "Need more dashboards?" prompt is the first element, its height is a lot smaller, because it is only a bit of text with a short, flat button. In this case, the height does not match the other DashbaordCards and the button and text overlap.

When the `AssetLimitAlert` card is not the first element in the row, its height is properly set to the height of the other DashboardCards.

**Comment by TCL735** [comment]
Therefore, we need to find a way for the `AssetLimitAlert` to correctly find and set the height of its container based on the heights of the other DashboardCards in view.
