### ISSUE TITLE
Scoping of v.windowPeriod.

### ISSUE THREAD

**Issue by wiedld** [influxdata/ui#4836]
Client examples included scoped use of windowPeriod declarations. The basic pattern of scoping is this:
* has the user already hardcoded what value of `v.windowPeriod` that they want?
  * yes --> do not calculate one for them.
  * no --> calculate and provide with query. 
* for scoped calculation:
  * where is the `v.windowPeriod` used?
  * what is the scope at the moment of it's use? Which timeRange is it in?
  * also be aware that user declaration of `v.windowPeriod` can be scoped.

## Summary of the current test cases, and the expected outcome.

```
// TEST CASE  --> use declared v.windowPeriod
// EXPECT: nothing injected
// IN PROD: error @5:1-5:25: variable "v" conflicts with option of same name
import "array"
v = {windowPeriod: 2444}
array.from(rows: [{x: v.windowPeriod}])

// TEST CASE  --> use outerScope windowPeriod, without a range in the query
// EXPECT: inject v.windowPeriod
// IN PROD: injects windowPeriod undefined
import "array"
array.from(rows: [{x: v.windowPeriod}])

// TEST CASE  --> use v.windowPeriod extracted from range transformation
// EXPECT: inject v.windowPeriod, using 120000
// IN PROD: no error. Does correct injection of v.windowPeriod = 120000
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> yield(name: "${v.windowPeriod}")

// TEST CASE  --> use v.windowPeriod from inner scope
// EXPECT: nothing injected
// IN PROD: it injects the -12h...not the 2444
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> map(fn: (r) => {
    v = {windowPeriod: 2444}
    return ({ r with _value: v.windowPeriod })
  })

// TEST CASE  --> use v.windowPeriod from inner scope, does not overwrite outer scope
// EXPECT: injects windowPeriod from outer UI variables
// IN PROD: incorrectly injects from the inner scoped range
import "influxdata/influxdb/sample"
import "array"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> map(fn: (r) => {
    v = {windowPeriod: 2444}
    return ({ r with _value: "foo" })
  })
array.from(rows: [{x: v.windowPeriod}])

// TEST CASE  --> detect v.windowPeriod in the inner lambda
// EXPECT: inject v.windowPeriod, using the range -12h
// IN PROD: is correct
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> map(fn: (r) => {
    return ({ r with _value: "${v.windowPeriod}" })
  })

// TEST CASE: timeRange variable bound by VariableAssignment statement
// EXPECT: inject v.timeRangeStop, v.windowPeriod 119833ms
// IN PROD: option v = {timeRangeStop: now(), windowPeriod: 119833ms}
import "influxdata/influxdb/sample"
import "date"
import "experimental"
truncated = date.truncate(t:v.timeRangeStop,unit:1m)
splitPoint = -1m
sample.data(set: "airSensor")
  |> range(start: -12h, stop: splitPoint)
  |> yield(name: "${v.windowPeriod}")

// TEST CASE: two timeRanges used. Should grab the proper one for windowPeriod.
// EXPECT: inject v.windowPeriod using the range -12h
// IN PROD: injects for the shortest range. In this case, the -15m.
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> yield(name: "${v.windowPeriod}")
sample.data(set: "airSensor")
  |> range(start: -15m, stop: now())
```

**Comment by wiedld** [comment]
Just added this test case as well, since in compounds a few scoping rules:
```
RAW = () => {
          from(bucket: "sample_data")
            |> range(start: -12h, stop: now())
            |> filter(fn: (r) => r["_measurement"] == "airSensors")
            |> filter(fn: (r) => r["_field"] == "co")
            |> group()
            |> sort(columns:["_time"])
            |> aggregateWindow(fn: mean, every:v.windowPeriod)
            |> drop(columns:["_measurement","_field","_start","_stop"])
            |> yield(name:"raw ${v.windowPeriod}")
          return true
        }
        RAW()
```

is passing integration tests on the PR for the fix.

**Comment by rockstar** [comment]
Below I went through each example until I started to get an idea of what the issue actually is. It sent me on quite the spelunking adventure, and I leave it here as a record of my past, for those who would like to walk where I walked.

It's pretty clear here that we're not only painted into a corner, but also stuck in a hole we've dug for ourselves. In an attempt to make the UI presentation better, we've starting teaching the UI more and more about the mechanics of flux, to a point where the only remedy forward would be to create something akin to a full-on flux pre-processor. I don't think that's an appropriate direction to go in.

I would like to find the best path forward to revert us back to having `timeRangeStart` and `timeRangeStop` provided by controls in the UI, and only specifying `windowPeriod` as part of a package deal with that. I'm not even sure what the use case is for using `windowPeriod` without the other range variables, but whatever it is, we should find an alternative way to provide that functionality.

-- 

This issue has a lot of cases in it, and it's probably hard to address them all separately, but I'd like to go through each test case and explain what I think should happen here:

```
import "array"
v = {windowPeriod: 2444}
array.from(rows: [{x: v.windowPeriod}])
```

This should not work in cases where `v` is provided. It'll break. The LSP currently shows an info (read: lint) message that one should not assign to `v`, and in the UI editor, it straight up shows an error message (as seen below). Maybe we can get a better error message, but that error message should be emitted from flux.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/60306/178626426-e548a28a-4266-4b25-8827-c00efba9cb37.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/60306/178638141-91e55b36-ac32-495e-8a4e-f1e9ed6b902b.png">


```
import "array"
array.from(rows: [{x: v.windowPeriod}])
```

This _should_ work. It should spit out a single row with an `x` value that corresponds with the `windowPeriod` provided by the ui.

```
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> yield(name: "${v.windowPeriod}")
```

This should also work, where the result is named the stringified version of whatever was provided as `windowPeriod` by the UI.

```
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> map(fn: (r) => {
    v = {windowPeriod: 2444}
    return ({ r with _value: v.windowPeriod })
  })
```

In the current Data Explorer, this returns rows with `_value` of `2444`, which is what I would have expected. I don't see the behavior where it's returning `120000`. Where does this occur?

 ```
import "influxdata/influxdb/sample"
import "array"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> map(fn: (r) => {
    v = {windowPeriod: 2444}
    return ({ r with _value: "foo" })
  })
array.from(rows: [{x: v.windowPeriod}])
```

I'm going to assume that this is just missing a `yield` by accident and add it in, as well as converting `{x: v.windowPeriod}` to `{x: "${v.windowPeriod}"}` as we can't represent a duration in column data. I'm not sure I completely understand the issue here. I'm having a hard time parsing 

> `// TEST CASE  --> use v.windowPeriod from inner scope, does not overwrite outer scope`
> `// EXPECT: injects windowPeriod from outer UI variables`
> `// IN PROD: incorrectly injects from the inner scoped range`

Does this mean it's injecting `2444`? In the Data Explorer right now, I'm getting `2m`. 

```
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> map(fn: (r) => {
    return ({ r with _value: "${v.windowPeriod}" })
  })
```

> `// EXPECT: inject v.windowPeriod, using the range -12h`

This is where I start digging into source. This expectation does not seem correct to me, and so I had to understand why this is the expected behavior. `v.windowPeriod` should be a package deal with `v.timeRangeStart` and `v.timeRangeStop`. When you eject from either of those, you own all the pieces from the fallout. We should not, under any circumstances, try and guess what the right `windowPeriod` is for a query, for all the reasons that are listed in this issue. That's the core of the issue. `v.windowPeriod` should just be some function of `(v.timeRangeStop - v.timeRangeStart) / NUMBER_OF_PIXELS` and that's that.

```
import "influxdata/influxdb/sample"
import "date"
import "experimental"
truncated = date.truncate(t:v.timeRangeStop,unit:1m)
splitPoint = -1m
sample.data(set: "airSensor")
  |> range(start: -12h, stop: splitPoint)
  |> yield(name: "${v.windowPeriod}")
```

Further backing up the previous assertion, we're trying to _guess_ what the user wants to do, instead of trusting the user to do what they want to do. If they want to take some runtime-provided variables in `v` and transform them, we should trust them that they know what they're doing. We should not try and dig into mechanics of flux and guess what the user wants.

```
import "influxdata/influxdb/sample"
sample.data(set: "airSensor")
  |> range(start: -12h, stop: now())
  |> yield(name: "${v.windowPeriod}")
sample.data(set: "airSensor")
  |> range(start: -15m, stop: now())
```

I'm glad we got to this one, which is the simplest example to provide for why we absolutely don't want to be parsing flux, checking some values, calculating a new value, and then providing it on the fly. If the first query opted into `v.timeRange*`, and the second query was just to provide some annotation to the graph, if we wanted to make that work, we'd then have to make the UI ast parsing pipe expression aware. This is, to some extent, re-implemented flux logic in frontend. We would do that, in hopes that we're adding value, but likely causing more confusion to the user who has no idea why it's working the way it is. We're creating "browserflux" here; kinda flux-like, but with some flourishes that wouldn't make sense otherwise.

> `// IN PROD: injects for the shortest range. In this case, the -15m.`

Aside, is it actually the shortest range, or is it just the second specified range?

```
RAW = () => {
          from(bucket: "sample_data")
            |> range(start: -12h, stop: now())
            |> filter(fn: (r) => r["_measurement"] == "airSensors")
            |> filter(fn: (r) => r["_field"] == "co")
            |> group()
            |> sort(columns:["_time"])
            |> aggregateWindow(fn: mean, every:v.windowPeriod)
            |> drop(columns:["_measurement","_field","_start","_stop"])
            |> yield(name:"raw ${v.windowPeriod}")
          return true
}
RAW()
```

After seeing the source that tries to guess at `windowPeriod`, this is a fine example of why we should not do that. In order for us to determine that the range is `12h`, the ui would have to understand (read: implement) the meaning of `now()`. `now` isn't a function, but an option. If the script contains `option now = () => 2030-12-25T00:00:00Z`, it means that whatever `windowPeriod` calculation would have to become aware of that. It's an arms race that isn't practical to keep up with.

**Comment by wiedld** [comment]
> In the current Data Explorer, this returns rows with _value of 2444, which is what I would have expected. I don't see the behavior where it's returning 120000. Where does this occur?

The testcases document what extern `v.windowPeriod` gets sent with the flux query to the backend. As an extern calculated by our UI frontend code. That is different from how flux runs it at runtime. The "expected" versus "actual" is what the UI code sees as the windowPeriod, and with or not it injects it (a.k.a. send as an extern).

I agree that we then paint ourselves into a corner. Since we take this UI calculated `v.windowPeriod`, and modify it for other features. Such as the pixel graph calculations, and then the re-calculation based on zoom.

**Comment by wiedld** [comment]
> That's the core of the issue. v.windowPeriod should just be some function of (v.timeRangeStop - v.timeRangeStart) / NUMBER_OF_PIXELS and that's that.

Our current product design is to first see if the duration (stop-start) is one of the preset durations (in seconds) here: https://github.com/influxdata/ui/blob/master/src/shared/constants/timeRanges.ts, and use that corresponding windowPeriod. If not --> then do math.

**Comment by wiedld** [comment]
Team decided not to fix the incorrect windowPeriod, rather to scope changes to only remove the undefined use cases.
