### ISSUE TITLE
Unable to Watch Build UI for OSS

### ISSUE THREAD

**Issue by syedalinaqi** [influxdata/ui#4865]
## About the bug
The UI for Influx isn't being build appropriately. After following the Guide, It gives weird **hmr** and **chunk not found** errors. 

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Run the Backend By compiling it from the InfluDB Repo
2. Fetch the Latest copy from `master` Branch or `OSS-2.1`.
3. Run `yarn run start`
4. Application Compiles Successfully

**Expected behavior:**
Expected to see the UI Running on Port 8080

**Actual behavior:**
Once the Port is opened, the UI keeps on loading and after a While I see the **localhost:8080/hmr** error or 
> Error importing `index.tsx`: ChunkLoadError: Loading chunk 68 failed.

**Visual Proof:**
![image](https://user-images.githubusercontent.com/3082612/175025761-bd16ee36-1acc-4569-a19b-7242db9bdd68.png)

## About your environment

**Environment info:**

- System info: Linux 5.10.102.1-microsoft-standard-WSL2 x86_64
- InfluxDB version: (Latest compiled from master)

**Additional Info**
Interestingly, If I just build the project with `yarn run build`, It compiles and if I pass the **ui-assets** path to the command `bin/linux/influxd`, It shows the modifications I made. 

The problem is live reloading. That isn't working and recompiling the UI for any small change takes around 10-20 Minutes which is a ordeal.

**Comment by syedalinaqi** [comment]
Hi @asalem1,  The error you had referenced seems to be inherently different then the one I am exepriencing. My error is related to initial loading while the one in the reference bug is related to the Chunk not found while navigating the application. For me, the Application isn't even starting. 
I **Hard Refreshed** it as well as **Cleared Sit Data** via Dev Console. I also tried checking it inside the **Incognito Window** but still the Same error.
![image](https://user-images.githubusercontent.com/3082612/175234730-79ffd1cb-2a42-4945-8963-4275afe76ee8.png)
And also the page loading time is more than 10 minutes which seems absurd (although even after that amount of time the page is still blank and it shows that the page is still loading)
![image](https://user-images.githubusercontent.com/3082612/175234957-e173a368-569c-440d-9042-9a87680ecdd1.png)


The Above Errors Occur Only if I comment out the `devServer.sockPath` inside the file `webpack.dev.ts`.
![image](https://user-images.githubusercontent.com/3082612/175233764-5d66c50b-03de-4f3a-8703-739ff9af982f.png)

Once the above is commented out, the aforementioned **Chunk error** occurs. If I don't comment it out and run it as is, I get the following error with additional **hmr** related errors:
![image](https://user-images.githubusercontent.com/3082612/175238820-bd0416a8-65ec-4b8a-b692-eb9e476af1e1.png)
With additional web-socket errors. connecting to `localhost:8080/hmr`.

The chunk error doesn't appear if I use the Master branch, instead only the `hmr` related error occurs.

**Comment by syedalinaqi** [comment]
@asalem1, Any update on this? Could you kindly help out in this. I have tried fetching a new OSS Version and Also using the One that's in the Release as well but got the same error in both cases. Will really appreciate your help on this. Thanks!

**Comment by syedalinaqi** [comment]
@asalem1 .. Thanks, That'd be great. Also, I noticed something else which could help. It seems that the file was found but it takes a-lot of time for it to load.
![image](https://user-images.githubusercontent.com/3082612/177619982-5079073d-79b0-452a-9dd8-605356b4463a.png)

Like here, the Single **71.js** chunck file took around 14 minutes while the normal timeout for the `chunckLoading `for webpack-dev is _30000ms_ which I changed to _1200000ms_, but _2 mins_ don't help us that much. So, I think what we need to know is why it's slow in this case but not production...? Is it related to my environment? Which I think isn't the case since the same error doesn't appear if I only do `yarn build:vendor` and then pass the build folder's path to the Backend with the --assets-ui args.

**Comment by syedalinaqi** [comment]
@dgnorton, Yes I did. I was able to build the backend with no problems and it started fine and was easily accessible on port **8086**. Now, when I build the UI Part from **OSS-Master** here, I run into the error mentioned above. I have tried other branches such as **OSS-2.1**, **OSS-2.0** and even **master** but got the same error on all. If I build it via `yarn build:vendor` and pass the build folder's path from UI to the Backend with the --assets-ui arg, it loads the modifications I had made. But when it's run via `yarn start` (dev mode), it gives the chunck load errors (as mentioned above).

**Comment by dgnorton** [comment]
@wbaker85 can you offer guidance here?

**Comment by wbaker85** [comment]
I can reproduce some of the difficulties here, and offer a clue as to what might be the problem, as well as a possible workaround:

- **Scenario**: Latest `influxdb` & latest `ui` (master branch of both)
  - Build the `influxdb` backend using `make build`
  - Start the `influxdb` backend
  - Start the `ui` in dev mode using `yarn start`
  - I observe that the UI is available on `localhost:8080`, hot reloading does not work, and I see the `WebSocket connection to 'ws://localhost:443/hmr' failed` error in the console.
  - I do not get any chunk loading errors.
  - In this state, I can make changes locally to the UI, but cannot see them until I refresh the page. I can see the changes when I manually refresh the page.
  - The `WebSocket connection to 'ws://localhost:443/hmr' failed` error suggests that the dev client is not able to connect to the dev server itself. Through some trial-and-error, I found that removing the configuration in `webpack.dev.ts` for `devServer.client.webSocketURL` (commenting it out and just using the default values) and restarting the UI in dev mode (using `yarn start`) results in hot reloading working as expected. So a workaround is to comment out [these lines](https://github.com/influxdata/ui/blob/23ef0b2e4deb3c31507b7d63c195a3134f4a667c/webpack.dev.ts#L51-L55) in `webpack.dev.ts`.

- **Scenario**: Latest `influxdb` & `ui` checked out at tag `OSS-2.1.0`
  - Build as per above, start UI in dev mode using `yarn start`
  - I do not get any chunk loading errors, and hot reloading seems to be working as expected

I cannot reproduce the chunk loading errors. I have seen these intermittently in the past, but do not see them now. The `webpack.dev.ts` changed between older commits at `OSS-2.1.0` and present, and it seems that this may have broken local development with OSS. Removing the specific `devServer.client.webSocketURL` configuration allows hot reloading to work for me with the latest UI. The UI at `OSS-2.1.0` started in dev mode seems to be working fine as-is for me.

Since you aren't getting chunk loading errors on the UI `master` branch, it would be interesting to see if hot reloading works for you when you remove the `devServer.client.webSocketURL` from `webpack.dev.ts` on that branch.

**Comment by syedalinaqi** [comment]
@wbaker85, I followed how you had explained the above but still got the `Chunk Loading Error`.
![image](https://user-images.githubusercontent.com/3082612/178500920-5a29a1fb-0968-4a86-a15e-36fcfa348e99.png)
Which _OS_ are you using? Could this possibly be because of **WSL2**? If so then why doesn't the same happens when we do it for the **influxdb** backend and check it on port _8086_?
