### ISSUE TITLE
Query Zoom (GA) - On/Off capability for adaptive zoom 

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#4988]
ACs
- User should be able to toggle on/off the adaptive zoom per cell
- Their toggle choice should persist for that cell
- The decisions that users make at the cell level will supersede any default settings
- All users with a Solona email address should automatically have the toggle turned ON for any NEW cell that a Solona client creates. (New cells for Solona should default to adaptive zoom being turned ON.)

_Implementation will depend on whether or not Solona is an org or an account._

The following are not requirements, but rather, they're potential implementation paths depending on if Solana is an Account or an Org:
- Ability to set an org-level default for adaptive zoom or digital zoom.
- Ability to set an account-level default for adaptive zoom or digital zoom.

**Comment by taramk** [comment]
Mock: https://www.figma.com/file/9iaD83d0YkKDYBEms5YKGM/windowPeriod-dropdown?node-id=350%3A1787

@Luckette I was hoping to link to some window period docs but I can't find anything that has a general definition that would cover both the query builder and the script editor. There's this flux documentation: https://docs.influxdata.com/flux/v0.x/stdlib/universe/window/

Let me know if you think that works, otherwise we could remove the link and request new docs.

**Comment by Luckette** [comment]
Yes, looks good, thank you

**Comment by TCL735** [comment]
The backend support for saving this property per cell is found here: https://github.com/influxdata/idpe/pull/15556

**Comment by TCL735** [comment]
At this time we are only able to do this at the cell level. Since currently there is no backend support for user or org settings, we will revisit this setting in the future.
