### ISSUE TITLE
Kodiak Tool - UI/Deployments Sync Team

### ISSUE THREAD

**Issue by hralexander** [influxdata/ui#4999]
UI/Deployments team has reached consensus, along with the leads of 2 (out of 3) UI teams, to add kodiak to the UI repo. QX team needs to review and add their perspective.

**Goal:** handle the density of PRs being merged in the UI, and have a formalized process which ensures only rebased-then-CI-passing commits get added to master branch.

**Proposed solution**: using autoupdate and automerge flags on pull requests (as is currently working in k8s-idpe).

**Spike research**: by qx team
**Putting kodiak in**: would be done by deployments team

**Comment by wiedld** [comment]
Information for the the other qx-team members to assess themselves:
 
* kodiak toml in k8s-idpe, what labels are used in the PRs, and at the kodiak docs again.
    * https://github.com/influxdata/k8s-idpe/blob/master/.kodiak.toml
* k8s-idpe has separate automerge  and autoupdate labels.
    * autoupdate label == keeps the PRs up to date.
    * automerge label == this merges the PR once all the requirements are fulfilled.
* The k8s-idpe kodiak.toml shows the settings, but does NOT include some important default settings (since we use the default):
    * we use the default automerge label (https://kodiakhq.com/docs/config-reference#mergeautomerge_label).
    * we require this label to be present, before any merging (https://kodiakhq.com/docs/config-reference#mergerequire_automerge_label)

**Comment by hralexander** [comment]
QX team is going to wait for github built mergequeues tool for this functionality.

**Comment by wiedld** [comment]
We did merge queues instead. Already done. Closing.
