### ISSUE TITLE
Multi Org Phase 1 - Adjust global header style per design input

### ISSUE THREAD

**Issue by wdoconnell** [influxdata/ui#5307]
Design has reviewed the implemented global header behind the feature flag, and would like the following adjustments to the current style:

1. 'Switch Account' button should be adjusted so that it is no longer in a hover state while the typeahead dropdown is expanded.
2. Dropdown should 'hug' items if there are below a given number (e.g., no extra space in the dropdown if there are only two items, see below).
<img width="271" alt="Screen Shot 2022-08-04 at 5 30 59 PM" src="https://user-images.githubusercontent.com/91283923/183082268-a8575b37-2fc9-4571-aac8-06b08d48eee7.png">

3. Test changes to search bar background, to see if a color aside from black (e.g., matching gray style) looks better but is still legible.

@Luckette @juliajames12

**Comment by ChitlangeSahas** [comment]
For #2 , the behavior seen is consistent across the Button Component in all over the App. I can fix it, but I think it's worth noting that it's not global header specific:

The hover state stays after click and needs a click outside to get rid of it.

https://user-images.githubusercontent.com/18511823/184192083-1777c1fa-54a6-4061-8d15-2124fc112682.mov

**Comment by juliajames12** [comment]
I spoke with @ChitlangeSahas about this over slack, but my recommendation is that we treat the "Switch" buttons differently than the other buttons because this is a special use case where we are allowing users to drill down to a submenu vs. go back to the main menu. Since those are two separate actions I don't think the button should stay active.
