### ISSUE TITLE
firstMile: CLI - Note what prereqs are needed for homebrew to effectively download

### ISSUE THREAD

**Issue by Luckette** [influxdata/ui#5377]
For some users, in order to download homebrew, they may need to upgrade their Mac. We should note what other prereqs are necessary in order for the download to be successful. Even if it's a general statement to make sure you have the latest upgrades to your homebrew and Mac OS. 

Note: This feedback came from Gary Fowler, we can contact him for more information about his experience if needed. 

Thoughts? Concerns? Feedback?

**Comment by Luckette** [comment]
@garylfowler Did I capture this correctly?

**Comment by garylfowler** [comment]
Quick clarification:  What I encountered was that because I was running a new MacBook Air with an M1 chip, I needed to install Rosetta since the CLI tool at that time was developed for Intel.

https://support.apple.com/en-us/HT211861

Not sure if we have upgraded our CLI tool since then or not.  Most users would have already installed Rosetta, but I hadn't since it was a new Mac.  If we haven't updated our CLI tool, we might need to note that.  It isn't really a pre-requisite of running homebrew or installing the tool, but it would be a pre-req for running the tool.
