### ISSUE TITLE
Bug - All Onboarding Wizards - Navigation - Scroll to top after clicking Next

### ISSUE THREAD

**Issue by david-rusnak** [influxdata/ui#5452]
Currently when navigating through the wizards, clicking `Next` takes the user to the midpoint of the next page. Users should be put at the top of the next page so they do not have to scroll.

**Comment by alexjw3** [comment]
So far on this issue, I have tried using window.scrollTo, both in a useEffect as well as within a function in the next onClick. Additionally, I have tried setting/using scrollTop with no effect, used useRef with no effect, used scroll element into view with no effect, as well as other scroll functions, all with no impact. Additionally, I tried creating a scroll to top button instead, also with no impact. I'm not sure what the problem is here, but hypothesize that it is in the way clockface interacts.
