### ISSUE TITLE
Data Explorer - Multi-Measurement Support

### ISSUE THREAD

**Issue by influx-product-manager** [influxdata/ui#5648]
## User Story

<p></p>

As a user, I want to be able to search fields and tags within all measurements so that I can find things even if I don't know what measurement they are in and I want to be able to pick multiple measurements so that I can find things in more than 1 individual measurement.

<p></p>

## Acceptance Criteria

<p></p>

- A new item will be available at the bottom of the measurement list labeled "select all" (at the bottom so that it doesn't just get checked out of ease)

- When select all is chosen, then no measurement filter will be added to the flux script (it will be like it worked previously when you could select a field or a tag first).

- A user will be able to select multiple measurements, not just one.

- When choosing select all, all other measurement boxes will be grayed out and then cannot be selected unless the user unselects the select all button

- When a user has chosen an individual measurement(s) and then chooses "select all" - the previous selections will be lost

<p></p>

## Notes

<p></p>

This is to answer the backlash of feedback from customers upset when we put forced measurement selection in place, and will buy us more time to add multi-measurement selection to the new script editor.

<p></p>

**Comment by mavarius** [comment]
The described behavior is really that of a "select none" rather than a "select all" which leads to some ambiguity. Could we have it instead be a checkbox for "All Measurements" which keeps the same behavior of disabling the others?

**Clicking "All Measurements" sets all items to unchecked and appears disabled**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/11937365/189040891-7a60dda7-ae78-488d-a88b-e0ed62048268.png">

**Clicking it again returns to normal selection behavior**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/11937365/189041599-92583350-8222-43ef-a36f-32b8da3928df.png">

**Multi-select enabled**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/11937365/189041724-33ef6cc0-4c93-4cc7-9557-e59ea8326de7.png">
