### ISSUE TITLE
Flaky test: cloud/subscriptions e2e

### ISSUE THREAD

**Issue by TCL735** [influxdata/ui#5738]
Cloud e2e tests for subscriptions are flaky. They seem very prone to 500 Internal Server Errors.

<img width="1404" alt="Screen Shot 2022-09-12 at 2 21 01 PM" src="https://user-images.githubusercontent.com/10736577/189760948-16c2f9b9-1d99-4041-9a4e-2be69692c577.png">

See examples of failures here:  
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/15447/workflows/0703027f-0ee3-42d3-be8d-557e9b4739e6/jobs/1019292  
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/15446/workflows/9861e87e-80b8-4c50-bd88-ad390620dbf9/jobs/1018935  
https://app.circleci.com/pipelines/github/influxdata/monitor-ci/15448/workflows/2f60c629-c6d6-4807-94a0-6fd832d29230/jobs/1019247

**Comment by subirjolly** [comment]
Tests were failing because of nifid issues and the fact that idpe disabled running ui tests and broken code went to production.

If subscriptions tests become a problem again, we can pick this up. But for now, I am removing myself as an assignee.

@kristinarobinson @TCL735 should we close this issue?
