### ISSUE TITLE
"Add import" code action fails

### ISSUE THREAD

**Issue by cannonpalms** [influxdata/ui#5895]
## About the bug

**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. Navigate to the script editor in data explorer
2. Use a function (e.g. `schema.fieldsAsCols()`) that is not a part of the `universe` namespace and thus requires an import
3. Move the cursor over the error and press `Ctrl+.` to bring up the Code Actions menu
4. Use the default action to "add import"
5. Failure.

**Expected behavior:**
I expect the appropriate import to be added to the top of my script.

**Actual behavior:**
Nothing happens, and an error appears in the console.

**Visual Proof:**

![add-import-code-action-bug](https://user-images.githubusercontent.com/2457559/192375306-6bbfaff2-80d4-4119-8c6b-4aae0ac6f041.gif)
## About your environment

**Environment info:**

**Config:**

**Logs:**

**Performance:**
Generate profiles with the following commands for bugs related to performance, locking, out of memory (OOM), etc.

```sh
# Commands should be run when the bug is actively.
# Note: This command will run for at least 30 seconds.
curl -o profiles.tar.gz "http://localhost:8086/debug/pprof/all?cpu=true"
curl -o vars.txt "http://localhost:8086/debug/vars"
iostat -xd 1 30 > iostat.txt
# Attach the `profiles.tar.gz`, `vars.txt`, and `iostat.txt` output files.
```

**Comment by wiedld** [comment]
Documenting this here for my future self. The payload:
<img width="622" alt="Screen Shot 2022-12-14 at 1 59 34 PM" src="https://user-images.githubusercontent.com/10232835/207726454-bc758ef3-e008-45cb-a063-204787bc93f4.png">

Error is then thrown in the monaco-editor.

**Comment by wiedld** [comment]
Ok. It's failing in monaco-editor. Reason is that the underlying vscode is hitting [this error,](https://github.com/microsoft/vscode/blob/c2a3e85d3c60870546a7769333cfe66cfb512a85/src/vs/editor/browser/services/bulkEditService.ts#L32), because it's expecting a `textEdit` field per [this type definition](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/languages.ts#1433), whereas what it's being given is a `text` field as per an older version of vscode [updated here](https://github.com/microsoft/vscode/pull/154275/files).

Suspect we have a mismatch in the various interdependent editor libraries used, such that we are passing an older typed object to a newer validation function.

**Comment by wiedld** [comment]
The latest monaco-editor uses vscode libraries (and typings) from a year ago. Don't think it's really wise to start down the path of upgrading that for monaco-editor. Instead, just reverting [this PR](https://github.com/influxdata/ui/pull/5793) will resolve this issue.

Cannot do so until after another PR merges -- where we remove the snapshot feature used (which requires the latest monaco-editor).

**Comment by wiedld** [comment]
The vscode ecosystem is a series of libs that work together. Much of this system works by message passing, or referencing objects in other libraries and passing on the vargs (variable length args) or payload. Basically, interfaces calling interfaces.

Many different layers often play a role in a single feature. The version bump of the `react-monaco-editor` in Sept 2022 enabled the lightbulb code action. But the bump in `monaco-editor`, done at the same time, broke it. Because somewhere down in the dependency tree, there is something transforming the vargs payload into the wrong/older internal typed struct. Then the internal struct is passed to `vscode` itself, where it fails the validation.

Monaco-editor itself (including the lock file) does not peg a version of these indirect dependencies. I have often found this be the case within this ecosystem, where only direct dependencies are cited. Although the package.json files often reference [`vscodeRef`](https://github.com/microsoft/monaco-editor/blob/main/package.json#L4) which I think refers to the vscode [`distro`](https://github.com/microsoft/vscode/blob/main/package.json#L4). (So I have a vague hypothesis -- I think much of this is pegged to a given vscode distro, and then the unlisted dependencies consumed are actually via that distro?)

This bug is not in Monaco-editor itself, since the version bump we currently use explicitly cites the breaking change use of [`WorkspaceTextEdit -> IWorkspaceTextEdit`](https://github.com/microsoft/monaco-editor/blob/9375d4ba65a3b50fd28569c588d2e279a13a757e/CHANGELOG.md#0340). And shows the proper transformation done [here](https://github.com/microsoft/monaco-editor/blob/f57624cdc137c581a056e112601f798e6ba50b01/src/language/typescript/languageFeatures.ts#L1127-L1139). This transformation uses the new `languages.IWorkspaceTextEdit` from monaco-editor-core, a.k.a. vscode. Therefore, I think the problem actually lies elsehwere. That it’s some other dependency (monaco-editor lock file listed or elsewhere) which is causing the issue.

This means that in order to debug, I believe the approach would be:
1. chase down where exactly is transforming this internal struct incorrectly.
    * Determine if the issue is some indirect dependecy somewhere using an old transformation/struct.
2. Fix it, or bump versions.
3. Figure out how to get our code to use the proper path.
    * Which lock-file to update?
    * Do I need to bump the distro, in order to get to the proper resolution? What mess does that bring in?
4. cross fingers, and hope we didn't break anything else.


Maybe I'm over-complicating it? If I had a better mental model of the ecosystem, then it could be a quicker fix. But right now the calculation is an unknown time of spelunking.


Note: my current mental model is only based upon the libs we specifically use to tie [together the different pieces](https://github.com/influxdata/ui/commit/c6597932850b39cf3244d0fae9453ec988763e52). And what I've stated above.

**Comment by wiedld** [comment]
The code action is turned off.

https://user-images.githubusercontent.com/10232835/211869693-ca5aba56-3770-4de9-83af-b46ecab23c7e.mov
