### ISSUE TITLE
Notebooks: As a user, if I see an intro video do I adopt notebooks more than someone who doesn't

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#596]
@mnorriswalker commented on [Tue Feb 02 2021](https://github.com/influxdata/influxdb/issues/20681)

A/B test for whether or note an intro video will drive more feature adoption

### Problem
There's a ability gap users must overcome to adopt a new feature like notebooks

### Evidence
In our early access test group, we saw users take some time to wrap their heads around notebooks

### Hypothesis
An explanatory video in the user's first notebook, will drive more 

### Prediction
Yes, videos help adoption. We'll need to make a shorter video though!

### Description
User Story
AS a cloud user 
WHEN I create my first notebook
THEN there is a video in the first cell

### Analytics and Measuring Success
_What are our primary and secondary objectives of success?_

#### Primary
Custom Event: `Create notebooks`

#### Secondary
Pageviews of /notebooks?

---
## Technical Notes

Variant already exists in the code behind a feature flag:

Feature Flags
`influx.set('flow-panel--youtube', true)`
`influx.set('molly-first', true)`

![image.png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/212a0c09-ae54-45bf-8b1e-47e476b7550e)![Peek 2021-01-29 15-28.gif](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/979f6857-901b-460b-8677-ad75cc49a1ff)

**Comment by drdelambre** [comment]
technical note on how feature flags are used in notebooks:
anything that starts with `flow-panel--xxx` only gates on panel creation, not on consumption. so if you made a notebook with the youtube flag on, someone else who views the notebook can still see that panel, even if they don't have the flag enabled. since the initial panel is being created by `the system` :tm:, we only need to gate whether that panel gets generated or not.

less winded version:
only `influx.set('molly-first', true)` is required

**Comment by mnorriswalker** [comment]
Experiment is built and ready to go but we're blocked until YouTube is added to the safe list for CSP @jzahnd 

![image (74).png](https://images.zenhubusercontent.com/5d928b2631e8dd0001222f82/b73e5878-ed53-42bc-9e1f-76a0edcfae2e)

**Comment by mnorriswalker** [comment]
Now running this A/B test
