### ISSUE TITLE
Cropped content in table; table doesn't scroll

### ISSUE THREAD

**Issue by mkmik** [influxdata/ui#6004]
## About the bug

**Steps to reproduce:**

* use a small screen (e.g. a laptop)
* make a query that produces a couple of tables (I used the flux profiler)

**Actual behavior:**

I see there is a row of data but I can only see a few pixels of it (see picture below). The table doesn't scroll vertically (tried with scrolling wheel / scrolling gestures)

By moving the splitter up and down I can fully reveal the row or I can fully obscure the row and thus cause it to move to the next page in the pager.

**Expected behavior:**

I expect to see the results without fiddling with the splitter.

**Visual Proof:**

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/52673/194158660-9a19d04e-5259-43fa-971f-29cb178536b8.png">

**Environment**

Chrome 105.0.5195.125 macos 12.5.1

**Comment by kristinarobinson** [comment]
Checking on which team to assign.

**Comment by TCL735** [comment]
This is a Giraffe issue.

The problem is with the measurement of the number of rows that can fit in the available space. Table headers, which are taller than a row, were not being counted correctly. Thus, the total running height was underestimated, and the available remaining height was overestimated, which leads to squeezing an extra row that should not be rendered.
