### ISSUE TITLE
Notebooks: instrument presentation mode

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/ui#603]
Also Instrument

> Export Task

**Comment by drdelambre** [comment]
why? it's awesome and half our feedback doing initial exploration stated that this functionality would replace most dashboard use cases for them

**Comment by mnorriswalker** [comment]
I didn't see anyone using it and I thought it was interface clutter. We could just instrument it for GA and see if it's being used?Good compromise. I don't feel too strongly about removing it but didn't see evidence to keep it.

**Comment by drdelambre** [comment]
i wouldn't expect a first time user to touch it, or it to test at all until people started relying on notebooks more as an artifact of exploration, and not just an exploration interface. This is one of the affordances we identified to help the user make that jump.

We added it after realizing that we'd worked ourselves into a froth internally about the importance of exporting a visualization cell to a dashboard, rushing to implement it, then observing that nobody ever touched the button, didn't even ask about it, didn't care when prompted to find it and click on it.

We chalked it up to a discoverability issue at first, but started asking users and in exploring the dashboard to notebook export vs embedding connection, or why you'd have a dashboard vs a notebook for certain use cases, it turned out that people would prefer to keep a notebook for as long as possible until the interface hits a problem with information density during a crisis: when you want to see a bunch of visualization cells at once to triage, before drilling down to the specifics of why a graph was or wasn't behaving. We circulated a video where Adam Anthony expressed this most succinctly during testing, but i have no idea where those went.

It's similar now to how dashboards work, with the ability to put text next to graphs but with the omission of horizontal cell positioning, and for a lot of use cases that were described to us, the cell ordering / scaling / positioning didn't really matter to the user, just information density. So we squeezed more cells on a page, just showing the cells that we'd show in the dashboards

**Comment by mnorriswalker** [comment]
@drdelambre - I will change this to instrument preview mode and assign myself based on your input

**Comment by mnorriswalker** [comment]
Done in version 72 of GTM Cloud App container. Also includes these events:

```
event('notebook_export_task', {exportType: 'create'})
event('notebook_export_task', {exportType: 'update'})
event('notebook_export_to_dashboard', {exportType: 'create'})
event('notebook_export_to_dashboard', {exportType: 'update'})
```
