### ISSUE TITLE
Spike: Persist Data Across Refresh for Queries Built In Data Explorer

### ISSUE THREAD

**Issue by ShmuelLotman** [influxdata/ui#607]
Part of a pleasant user experience when interacting with complex data is the ability to have the query state persist through refreshes so complex/nested queries are not lost and the user doesnt have to restart the entire process from step one. 

From what I understand, there have been a number of engineers that have attempted this work in the past and have encountered issues. If so, any comments and/or thoughts about this effort would be appreciated.

**Comment by hoorayimhelping** [comment]
@russorat @ShmuelLotman 

When should cached data be invalidated?

Does the cache need to be invalidated when the user finishes writing a query and saves it to a dashboard?

What about temporally? If I'm messing with a query in the afternoon, then I pack it up for the evening and get back to work the next morning, am I going to see my cached work from yesterday?

Does there need to be a way to clear out the query builder state so that I don't have to go through and close out each individual box from the query builder state that's cached?

**Comment by russorat** [comment]
@hoorayimhelping right now, we are going with never invalidating the cache assuming it's local to the user's browser.

re: does there need to be a way to clear state?
clicking a new bucket will do that today. i don't think we need it yet but we will see based on user feedback.

**Comment by hoorayimhelping** [comment]
>clicking a new bucket will do that today. 

i've been using this and working on it for over a year and didn't know that. that isn't obvious at all :( what do you think about adding a button that does that? #619

**Comment by russorat** [comment]
@hoorayimhelping yeah makes sense to add that if people are frustrated with adding and removing a bunch of DE boxes. Great follow on once we get some feedback.

**Comment by jzahnd** [comment]
Closing due to age
