### ISSUE TITLE
Homepage - JavaScript/Node.js icon and text look out of alignment compared to the other icons...

### ISSUE THREAD

**Issue by ALuckette** [influxdata/ui#6119]
## Issue
- The JavaScript/Node.js icon and text look out of alignment compared to the other icons...

## Screenshot
![Image](https://user-images.githubusercontent.com/112978673/196710082-92d7f835-0e6d-464d-8f1a-2c8fa6bde9ef.png)

**Comment by blegesse-git** [comment]
that's interesting. In prod or locally, I don't see any misalignment of the Node text or icon. Looking at your screenshot, I think the text looks off because of its length. Python, Go, and Arduino are much shorter and take up less space compared to JavaScript/Node.js. Is this also happening in other environments or just tools? @ALuckette

**Comment by kristinarobinson** [comment]
Update label to refer to JS only
