### ISSUE TITLE
Remnants from Previous Query is shown in Schema Browser when doing a new Query

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6201]
When selecting a measurement that has multiple tag keys and values and then switching to a measurement that has only 1 tag key, I am observing that it is showing in the list tag keys from my previous query, even though they are not applicable to the measurement I have switched to (somehow the tag keys are being cached, maybe?)

See video..  I can invite you to my org to reproduce if you can't reproduce on your own.

**Comment by garylfowler** [comment]
https://user-images.githubusercontent.com/97983559/198720359-637aee8b-7140-4da2-94c3-9be474dac141.mp4

**Comment by appletreeisyellow** [comment]
This bug can be reproduced by setting the feature flag `newQueryBuilder` OFF

* When the feature flag is OFF, [this query](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/tags.tsx#L94-L105) will run. Seems like this query get more values than tag keys.
* When the feature flag is ON, [another query](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/tags.tsx#L107-L123) will run and it returns the correct list of tag keys. 

I'm wondering if we need to have `newQueryBuilder` in the new script editor. Seems like this is a feature flag for old Data Explorer and Notebook. 

To fix this bug, we should:
1. re-write the [first query](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/tags.tsx#L94-L105)
2. remove the feature flag `newQueryBuilder` in the [if statement](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/tags.tsx#L107)


FYI: @garylfowler checked on ConfigCat that this feature flag is on by default, and only one customer has this feature flag off

**Comment by appletreeisyellow** [comment]
The other places that used `newQueryBuilder` is the old Data Explorer and Notebook with the work related to Force Measurement Selection #4253

Since the new Script Editor doesn't have a query builder, which looks like below, so we can remove the `newQueryBuilder` check in the if statements for [tag keys](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/tags.tsx#L107), [tag values](), [fields](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/fields.tsx#L96), and [measurements](https://github.com/influxdata/ui/blob/master/src/dataExplorer/context/measurements.tsx#L79).
<img width="777" alt="Screen Shot 2022-11-03 at 12 40 32 PM" src="https://user-images.githubusercontent.com/14298407/199795168-0a9972f1-df0b-4c52-bfec-36f32de1c94d.png">
