### ISSUE TITLE
Spike: Can we shrink our monaco-editor?

### ISSUE THREAD

**Issue by rockstar** [influxdata/ui#6239]
![image](https://user-images.githubusercontent.com/60306/199589201-4e4cb131-fe1b-47ac-bcfa-6f72b532eca8.png)

`monaco-editor` accounts for almost 1/3 of our webpack bundle size. Maybe that's just the state of affairs, but it'd be nice if we could investigate the `features` attribute of `MonacoWebpackPlugin` and see if we can turn off some features and deliver a smaller bundle as a result.

**Comment by wiedld** [comment]
Agreed with overall premise. To investigate using the `features` part of the webpack plugin, to reduce payload size. We were using this approach before, but removed it since there was not a significant impact on page load time. But it's always worth a re-visit.

.

## Previous code, using `features`
* removed code in [this PR](https://github.com/influxdata/ui/pull/4293), while also bumping all the major editor libs.
* there was [increased bundle size](https://github.com/influxdata/ui/pull/4293#issuecomment-1086540589), but [no significant increase in page load time](https://github.com/influxdata/ui/pull/4293#issuecomment-1092291553).

.

## Current (as of 2022/11/09) re-done bundle analysis:
Analysis done using [webpack query analyzer](https://webpack.js.org/api/cli/#analyzing-bundle).

### All bundles:
All bundles are not served for all UI subapplications. So this represents all bundles across the app:
<img width="1200" alt="Screen Shot 2022-11-09 at 12 55 57 PM" src="https://user-images.githubusercontent.com/10232835/200941075-8ff20673-ae74-41dd-8e6e-4341fd85e08a.png">

Usually one chooses the entry point for this analysis, but the webpack bundler analyzer could not parse that. So instead, I attempted an ad hoc analysis below.

### Monaco-editor bundles:
Gzipped size (what's transmitted over the wire):
<img width="350" alt="Screen Shot 2022-11-09 at 12 59 24 PM" src="https://user-images.githubusercontent.com/10232835/200941527-8b4fb520-7619-488c-bbcb-13008e5d1963.png">


**Total:** (833.74+107.54+72.83)/4780 = **21%**

Note that the json.worker is only sent when we are using a json editor. But that doesn't really move the needle.

**Comment by rockstar** [comment]
We've been talking very seriously about abandoning the chunking, mostly because it causes many more problems than it solves for us. It's good analysis, to see it through the lens of chunks, but it's probably not the be-all-end-all for us.
