### ISSUE TITLE
notebooks don't support multiple tabs

### ISSUE THREAD

**Issue by genehynson** [influxdata/ui#626]
If you open two tabs of the UI and navigate to different notebooks in each of them you'll notice a very strange flashing effect. This is happening because each of the tabs are fighting over local storage and keep overwriting the currently saved notebook id.

https://user-images.githubusercontent.com/6411855/107101992-e4d43080-67cd-11eb-80f3-4a73df549bd5.mov

**Comment by drdelambre** [comment]
last time we cleaned up a bunch of these, we found that the issue existed not in the local storage eventing mechanism or in the context providers themselves, but were subtly hidden in the panel's themselves not being able to correctly handle data being pushed from the other direction (bubbling up from the data source, and not pushed down from the interface).

sometimes they were useEffect hooks that had objects as diff keys instead of strings / numbers. sometimes it was that callbacks that utilized partial types weren't updating the state from the provider before smooshing the objects together. This should only get worse as we start introducing more complicated sharing paradigms.

anywho, take it on a panel type by panel type basis, or you might drive yourself insane. i hope this comment saves times
