### ISSUE TITLE
Notebooks: I can query my data without aggregation

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#650]
As a InfluxDB Cloud user, I can view the unaggregated results of a query so that I can understand the data being returned.

### Scenario: Remove Aggregate Functions
Given: I have a notebook open with a metrics selector cell
When: I select a measurement, tag, and/or field
And: I click preview
Then: There is no aggregate function applied

### Scenario: Too large
When: The query returns too much data
Then: Then a message is shown that the data is truncated and the truncated data is shown

### Technical Notes
  - The aggregation logic is going to move to the visualization cells in the notebook
  - The query built behind the scenes should not have an aggregate attached to it
  - We should investigate ways to limit the data returned, possibly using limit or sample. 100,000 of results will not be useful to the UI. We should target < 100 per series and no more than 20 series if possible.

### Design Notes
- Mockup
  - https://www.figma.com/file/8S8IH8mimYIwanZ6keIQ6U/Notebooks-Prototype?node-id=1631%3A175

**Comment by drdelambre** [comment]
the only reason we added aggregation to the query in the first place was because too many queries were coming back too large, taking too much time, or just dying on the user. it doesnt matter if we move default aggregation somewhere else, we still need to fetch results to display them. this is going to require query pagination, done on the backend, or else the interface crawls to a halt and dies on the amount of data coming back for anything non trivial.

i see this ticket in the epic, but not one that captures the query pagination work marked as a blocker.

This is not a problem confined to notebooks either, any time you save a task from data explorer, there is an implicit down sampling being appended to your generated query. The UX treatment doesn't change the underlying issue, and we should address that issue of removing the automatic aggregate window requirement in it's own epic

**Comment by russorat** [comment]
@drdelambre let's open the request to the flux team for query result pagination. i can't find one already.

because the metrics selector drives users to a single measurement -> field combo, and we are thinking critically about performance after GA, i'd say slap a `limit(n: 100)` on there for now and work with the flux team to get the apis we need.
