### ISSUE TITLE
User Confusion when no table/measurement is chosen

### ISSUE THREAD

**Issue by garylfowler** [influxdata/ui#6601]
If a user utilizes the SQL/Script Editor and selects only a bucket without a measurement and hits run (without manually modifying the SQL statement), the user will get back a long complicated error message, like:

executing query: failed to create Flight record reader: arrow/flight: could not create flight reader: arrow/ipc: could not read schema from stream: arrow/ipc: could not read message schema: rpc error: code = InvalidArgument desc = Error while planning query: Schema error: No field named 'time'.

We need to come up with a way to make this a better user experience.  Some thoughts:

Could we supercede this from happening by disabling the run button until a from exists?  This may not be possible since we aren't examining the SQL statement, but then could we do it when the user hits "run" (check to make sure it has a "from" specified) before we execute the query and inform the user they need to add a from clause in their statement?

Does it make sense to enhance the lower levels to report a more friendly message (vs. making the UI smarter) to address this?

**Comment by appletreeisyellow** [comment]
This is fixed by disabling the run button until a from exists in https://github.com/influxdata/ui/pull/6722

<img width="1481" alt="Screen Shot 2023-06-07 at 11 07 55 AM" src="https://github.com/influxdata/ui/assets/14298407/cbe2f534-77dc-449f-af0b-60ee200ebb97">


https://github.com/influxdata/ui/assets/14298407/3a534683-4d15-479a-8786-36b863518d7c
