### ISSUE TITLE
Tasks: After i manually run a task, i expect to be taken to the task runs page

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#724]
GIVEN: i am on the tasks list page AND i want to manually run a task
WHEN: i click on the Run Task option in the gear icon and the manual task run is successfully kicked off
THEN: i would like to be redirected to the task runs list page, with an entry for my newly created manual run

WHEN: the task run fails to start
THEN: i see a notification of the error and i stay on the same page

**Comment by Asalem1** [comment]
This one is actually a little trickier to sort out since we would need to poll the API until the task is resolved (failed or succeeded). Right now, what we can do is get all the run tasks by the task ID that and check the status once the task has been scheduled, but that doesn't guarantee that the task will have been resolved by the time the task is running. Placing an artificial timer (say, 1 second), could resolve this issue for us but there's no guarantee, not to mention the added latency that this would add to the app unnecessarily

**Comment by russorat** [comment]
@Asalem1 the ask here isn't to wait until the task completes successfully. We just need to "schedule" it and redirect to the tasks run page, where it will show as "scheduled".
