### ISSUE TITLE
Inf in query result rendered as NaN in "view raw data"

### ISSUE THREAD

**Issue by wolffcm** [influxdata/ui#804]
**Steps to reproduce:**
List the minimal actions needed to reproduce the behavior.

1. In the Data Explorer page in the 2.0 Cloud UI, enter this query: `import "array" array.from(rows: [{a:1.0}]) |> map(fn: (r) => ({a: float(v: "inf")}))`
2. Click on the `View Raw Data` toggle
3. Note that the column `a` has the value `NaN`
4. Click on `CSV` button to download the CSV for the result
5. Look at the CSV therein and see the expected value for column `a`, which is `+Inf`

**Expected behavior:**
`+Inf` and `-Inf` values in query results should render as such in the `View Raw Data` view.

**Actual behavior:**
`+Inf` renders as `NaN`.

**Environment info:**

Cloud 2.0

**Comment by mtian725** [comment]
This issue actually extends to the `Table` view in explore as well. This is due to an issue in Giraffe repository rather than in in the UI repository. At the very top of pyramid, the query results are passed to the function `getVisTable` which formats the result, which uses the `fromFlux` function from Giraffe.

The screenshot below shows the query result before and after line of code that utilizes the `fromFlux` operation. The console log marked `files` is the data before the result is formatted. `+Inf` is there, but after it is formatted. It is converted into `NaN`. This is passed as props into other components such that all visualizations will be seeing  `NaN` instead of `+Inf` or `-Inf`.

![InkedInkedScreen Shot 2021-07-08 at 7.05.35 PM_LI.jpg](https://images.zenhubusercontent.com/60be52f95b600c6c0157735b/3f73130f-4a03-436e-bfbf-7470bf274117)


The `fromFlux` operation converts `+Inf` and `-Inf` into `NaN` because of the line of code below. Column type is a `number` for `+Inf` and `-Inf`, and the Number() cast turns it into `NaN` because `+Inf` and `-Inf` are not valid numbers.

![Screen Shot 2021-07-08 at 7.56.44 PM.png](https://images.zenhubusercontent.com/60be52f95b600c6c0157735b/386d4637-21dc-40cc-a839-630f64f03230)

However, changing this will affect how the other graph visualizations render it, so will need to account for those.

**Comment by hoorayimhelping** [comment]
One potential solution is to consider rendering an asymptotic line for ±Inf

https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Hyperbola_one_over_x.svg/1600px-Hyperbola_one_over_x.svg.png

https://en.wikipedia.org/wiki/Asymptote#Vertical_asymptotes
