### ISSUE TITLE
Epic: UI Token Redesign

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#805]
### Target Customer / Background data / Context / Market Size
The user for this is someone who needs to generate a specific token to use for connecting to our platform outside of the UI.

### Goals
U
Update the tokens page in the UI to allow users to create and manage more detailed permissions for each token, and display token only at creation time.

### Acceptance Crit
 - as a user, i would like the ability to choose the resource types and the action a token can perform
 - as a user, i would like the ability to clone an existing token, which would copy the permissions into a new token
 - as a user, I would like a visual warning that a token can only be seen the one time It is generated.
 - as a user, I can only see the token at the moment I generate it, never after.  
 - as a user, I can only configure individual resource-specific read, write permissions for telegraf and buckets.
 - as a user, I want the list of the resource types sorted in priority order, and the list of resources will be alphabetical order.
 - as a user, I would like the ability to filter the detailed resource lists for buckets and Telegraf configs with a search bar.
 - as a user, I would like the ability to view the permissions associated with existing tokens, but I cannot edit them.
 - as a user, I would like the ability to add a description to the token when I create it, or after I've generated it.

 - ~as a user, i would like the ability to see the last time a token was used (this might not be possible without an API change)~
 - ~as a user, i would like the ability to sort by the last time the token was used (this might not be possible without an API change)~
 - ~as a user, i would like the ability to create a "telegraf" token which could be used to fetch a specific telegraf config and write data to a specific bucket.~
 - ~as a user, i would like my token obfuscated in the ui~

### Release Plan
 - This code will be put behind a feature flag so that it can be enabled on a specific date.

### Team
 - Anchor / Dev Champion - Palak Bhojani @Palakp41 
 - Product Manager - @russorat 
 - Design

### Technical Notes
 - Here is the API to create authorizations (tokens): https://docs.influxdata.com/influxdb/v2.0/api/#operation/PostAuthorizations
 - The UI does not need the capability to manage the permissions on an individual resource, but if a user creates a token to do so via the api, the UI needs to be able to display that cleanly.
 - I would also like to rename this page "API Tokens" to reduce confusion since that's what they are called in other tools.
  - The UI will need to modify its back-end API to use the new OpenAPI with the Cloud specific implementation.
  - For OSS, existing implementation will remain in place.

Out of scope
- From the Telegraf flow, regenerating a token is out of scope. 

Related issues:
 - https://github.com/influxdata/influxdb/issues/17179
 - https://github.com/influxdata/influxdb/issues/18887
 - https://github.com/influxdata/influxdb/issues/20466
 - https://github.com/influxdata/influxdb/issues/19770
 - https://github.com/influxdata/influxdb/issues/19627
 - https://github.com/influxdata/influxdb/issues/15961

Link to Figma
https://www.figma.com/file/1VaHno7NzQTFvzRtCnROay/Token%2FSecret?node-id=423%3A3704

**Comment by aanthony1243** [comment]
I do like the idea of having a token that does specific buckets, "and the rest!". Essentially, to create a bucket-limited all-access token.  Or a read-all-buckets, read-write UI resources.  

 I'm not convinced that we need to have fine-grained selection of specific UI/metadata resources, but I don't object to having this in the UI as it's likely that we will continue supporting this into the future.   

We are going to check that having an incomplete list of resource types in token creation/authorization does not have any problems, (e.g. if we use an enum to look up permissions in a list).

**Comment by jdstrand** [comment]
> as a user, i would like the ability to choose the resource types and the action a token can perform

IME, this seems like a reasonable idea, but to allow arbitrary combinations of permissions will provide a poor experience since many (most?) combinanations won't be useful and frankly, haven't been widely tested. More concretely, having the UI help users create useful tokens I think is a good idea (eg better token creation for buckets, perhaps tasks, maybe others) but having the UI allow users to create arbitrary tokens will add frustration and I fear support costs since only some permission combinations are useful. Eg, someone picking 'read' for dashboards thinking it is going to allow viewing dashboards may end up with the expected experience since other permissions might also be needed.

It is true that the /api/v2/authorizations is there to be used and it is documented so one can very reasonably assert that the UI should allow creating any token. However, in addition to the above, another problem is that there are existing and historical security bugs wrt token creation as well as how the system enforces tokens with novel permission combinations and we need to go through the authorizations system to fix these problems and make sure it is working correctly (this work has started but is a long haul). Couple that with the design ideas around adding more roles (we have 'owner' and 'member' but only owner is used AFAIK) and I think it is premature to open the floodgates of arbitrary token creation in the UI.

Have users asked for this feature specifically or are they wishing for a way to create tokens that allow doing useful things? I suspect even if they asked for it specifically, they really would want to be guided towards making useful tokens. Perhaps this can be scoped down to these useful combinations? We have all access, org unscoped bucket and scoped bucket access today. What else would be useful? Answering that question might provide insight into adding new roles as well.
