### ISSUE TITLE
Static Legend: Integrate Giraffe changes into UI

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/ui#806]
### Background
We need to integrate the giraffe Legend work into the UI

### Acceptance Criteria
- [ ] We're on the latest version of giraffe that includes Legends
- [ ] as a user, when i configure a graph or band graph in the UI, then I have the option to always display a legend on the bottom of the cell.
- [ ] as a user, when i enable the legend on a cell, no changes to hover tooltip display when hovering over different parts of the graph
- [ ] as a user, I can choose to configure whether recent time values will be displayed in the legend
- [ ] as a user, I can choose the height of the static legend in a configuration option

**Comment by TCL735** [comment]
This story is specific to the work of integrating the "Static Legend" into the UI.

Additional changes such as [sort order](https://github.com/influxdata/giraffe/issues/151) should be tracked in a separate story. Mainly, this is due to feature flagging. Static Legend will have its own feature flag, while the sort order feature can use the existing "legendOrientation" feature flag.
