### ISSUE TITLE
Notebooks: Query builder only shows 100 buckets

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#839]
as a user in an org with 100 buckets, it would be useful to be able to filter the list of buckets shown using text input.

![image](https://user-images.githubusercontent.com/4805997/111183563-43c75b00-856d-11eb-8e3b-0f9cd10a6a0f.png)

**Comment by Asalem1** [comment]
@russorat i think this is currently allowed behind a feature flag with @jrenee42 's recent changes

**Comment by russorat** [comment]
no, @jrenee42 is only for variables. this would be for areas of the app where you can select buckets from a dropdown.

**Comment by drdelambre** [comment]
did some digging
the typeahead dropdown mechanism isn't it's own component in clockface, don't know how we got collectively spun around on that one. there is a component in src/variables/components/TypeAheadVariableDropdown, but that component is tightly coupled to the variable redux store details. generalizing the component is a bit more of a task than we had estimated in planning, so i'm flagging that here and, since this ticket now encompasses making this interaction from scratch, bumping that estimation to a 5 based on how long it took the original one to be implemented

**Comment by barbaranelson** [comment]
The bucket list in the query builder in notebooks is filterable, but has a hard limit of 100 buckets.  Can we bring in whatever logic we have in the rest of the UI to show a much larger list of buckets?

Changing the title to match the remaining issue.
