### ISSUE TITLE
Notebooks: I can select more than one metric in a notebook

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#884]
right now, the metric selector only allows you to select a single field for the query. This story would allow the user to select multiple fields in the metric selector.

as a user, i would like to select more than one field in the metric selector.

**Comment by mnorriswalker** [comment]
@gefaila - Tagging you so you can watch this Issue. Thanks for raising!

**Comment by drdelambre** [comment]
we currently use the field + measurement filtering as a way for the user to explore their existing schema by being able to drill down with only partial knowledge of their dataset. by allowing the ability to filter by multiple fields, it means that the large selection box below removes that utility. you wont be able to find out what tags belong to a field, because we would need to keep all fields in that list to allow for a user to select the other one.

don't know where to go with this one.

**Comment by barbaranelson** [comment]
Closing out, as we've moved metric selector.
