### ISSUE TITLE
Notebooks: always show the vizualization options

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#913]
It's a little jarring to have so much stuff show when you hover over a graph. should we just always show it?

![image](https://user-images.githubusercontent.com/4805997/111728458-27a41200-882a-11eb-8730-5f4b211efaf7.png)

**Comment by drdelambre** [comment]
yeah.. we hid it originally because there were too many pixels dedicated to maintaining the structure of the notebook, and not the information that the flow was trying to show. it always had the discoverability issue though, so the solution isn't perfect (better than the "hide everything behind a hamburger" attempt though!)

lets put the visibility toggle in a feature flag so that we can test the always on version to make sure it makes sense on the lifecycle of a notebook (creation, maintenance, documentation, etc). it's definitely more of a feel, and you can't feel it until we try it!

**Comment by drdelambre** [comment]
rolling that comment on back..
for some reason this mechanism was what was causing the "aggregate window" problem, so i'm going to rip it all out

if it's weird, we can add it back, but it doesn't make sense to rewrite that focus mechanism just to remove it
