### ISSUE TITLE
Pencil icon to edit cell name is really far away from the text

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#918]
user commented that the pencil icon is really far from the text of the cell title. Is there a way we can bring those closer together?

![image](https://user-images.githubusercontent.com/4805997/111834082-5238ae00-88b0-11eb-89fd-435385c03740.png)

**Comment by Asalem1** [comment]
@juliajames12 would love to get your design thoughts on this

**Comment by juliajames12** [comment]
@Asalem1 I can definitely see it being an issue due to how small and far it is from the title (vs. the green checkmark icon below which holds more visual weight). I would place it right after the title name to make it easier for users to locate edit.

![Cell Title Edit (1)](https://user-images.githubusercontent.com/81173353/113908143-36844180-97a4-11eb-88a0-7a3f8275dd38.png)
