### ISSUE TITLE
Test Maps: More link is broken

### ISSUE THREAD

**Issue by russorat** [influxdata/ui#997]
After giraffe issue is fixed, pull in the latest giraffe version and test locally. Link to giraffe issue: https://github.com/influxdata/giraffe/issues/519

This link needs to be updated. Let's use this link when it is live: https://docs.influxdata.com/influxdb/cloud/visualize-data/visualization-types/map/

![image](https://user-images.githubusercontent.com/4805997/112684033-b1a63900-8e2f-11eb-9042-faef37e3e68e.png)

**Comment by Palakp41** [comment]
This is happening in giraffe: https://github.com/influxdata/giraffe/blob/master/giraffe/src/components/Geo.tsx#L227.

**Comment by russorat** [comment]
here are the current limits: https://github.com/influxdata/giraffe/pull/280/files#diff-f080501255ef5a922abbdf6618fa46f5e86b12fb0ba765fdd400325f9993f634R39

**Comment by zoesteinkamp** [comment]
Alright so with this link updated this issue is closed. Also i checked with the truncated limits and although mapbox does not have any specific defined limits in the docs. And i did test the marker map since thats currently active map and it seems like beyond 2000 led to lag. I am writing and linking a separate issue to determine if we cause the lag or if its mapbox. The issue is   527 in gifraffe
